<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Fazy') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->   
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <?php if ($this->activeProject->isActive() && $this->accessReleaseAndPhaseManagement): ?>
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array('id' => $this->phase->getId()), 'phase_edit') ?>"><?php echo $this->t('Edytuj') ?></a></li>
          <?php if ($this->phase->getExtraData('taskCount') == 0): ?>
            <li class="button_link_li"><a class="j_delete_phase button_link" href="<?php echo $this->url(array('id' => $this->phase->getId()), 'phase_delete') ?>"><?php echo $this->t('Usuń') ?></a></li>
          <?php endif; ?>
        <?php endif; ?>
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array(), 'task_list').'?phase='.$this->phase->getId() ?>"><?php echo $this->t('Zadania') ?></a></li>
      </ul>
    </nav>
    
    <div class="textLabelEditor">
      <div id="text" class="content_label_title">
        <?php echo $this->escapeQuotes($this->phase->getName()) ?>
        <?php if ($this->phase->getEndDate(true) < time()): ?>
        <span class="isEnded"><?php echo $this->t('Zakończona') ?></span>
        <?php endif; ?>
      </div>
    </div>    
    <div class="contentLRtable">
      <div class="contentProperties_left">
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><b><?php echo $this->t('Wydanie') ?></b></div>
          <div id="text" class="content_label"><?php echo $this->escapeQuotes($this->phase->getRelease()->getName()) ?></div>
        </div>
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><b><?php echo $this->t('Opis') ?></b></div>
          <div id="text" class="content_label"><?php echo $this->escapeQuotes($this->phase->getDescription()) ?></div>
        </div>
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><?php echo $this->t('Liczba zadań') ?></div>
          <div id="text" class="content_label">
            <a href="<?php echo $this->url(array(), 'task_list').'?phase='.$this->phase->getId() ?>"><?php echo $this->escapeQuotes($this->phase->getExtraData('taskCount')) ?></a>
          </div>
        </div>
      </div>
      <div class="contentEditUser_right">        
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><b><?php echo $this->t('Data rozpoczęcia') ?></b></div>
          <div id="text" class="content_label"><?php echo $this->phase->getStartDate() ?></div>
        </div>
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><b><?php echo $this->t('Data zakończenia') ?></b></div>
          <div id="text" class="content_label"><?php echo $this->phase->getEndDate() ?></div>
        </div>
      </div>
     </div>
    
  </article>    
</section>

<?php echo $this->partial('popups/delete-phase.phtml');