<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->emailT($this->name, 'subject') ?></title>
</head>
<body>
  <h1><?php echo $this->emailT($this->name, 'Witaj __fullname__!', array('fullname' => $this->user->getFullname())) ?></h1>
  <p><?php echo $this->emailT($this->name, 'Utworzono dla Ciebie konto w serwisie. Kliknij w poniższy link aby ustawić hasło.') ?></p>
  
  <p><?php echo $this->emailT($this->name, '__beginLink__USTAW HASŁO__endLink__', array(
    'beginLink' => '<a href="'.$this->url(array(
        'uid'  => base64_encode($this->user->getEmail()),
        'code' => $this->user->getToken()),
      'user_create_password').'">',
    'endLink'   => '</a>'
  )) ?></p>

  <p><?php echo $this->emailT($this->name, 'Pozdrawiamy') ?></p>
  
</body>
</html>
