<div id="j_popup_delete_attachment" title="<?php echo $this->popupT('delete-attachment', 'Usuwanie załącznika') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-attachment', 'Czy na pewno chcesz usunąć ten załącznik?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
/* ]]> */
</script>