<div id="j_popup_delete_avatar" title="<?php echo $this->popupT('delete-avatar', 'Usuwanie avataru') ?>">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-avatar', 'Czy na pewno chcesz usunąć avatar?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
  
  var popupYesNoName = 'delete_avatar';
/* ]]> */
</script>