<div id="j_popup_delete_task" title="<?php echo $this->popupT('delete-tasks', 'Usuwanie zadania') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-tasks', 'Czy na pewno chcesz usunąć wybrane zadanie?') ?></p>
</div>

<div id="j_popup_delete_tasks" title="<?php echo $this->popupT('delete-tasks', 'Usuwanie zadań') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-tasks', 'Czy na pewno chcesz usunąć wybrane zadania?') ?></p>
</div>

<?php echo $this->partial('partials/popups.phtml'); ?>

<script type="text/javascript">
/* <![CDATA[ */
  var popupYesNoName = ['delete_task', 'delete_tasks'];
/* ]]> */
</script>