<div id="j_popup_delete_tag" title="<?php echo $this->popupT('delete-tag', 'Usuwanie tagu') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-tag', 'Czy na pewno chcesz usunąć ten tag?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
  
  var popupYesNoName = 'delete_tag';
/* ]]> */
</script>