<div id="j_popup_delete_test" title="<?php echo $this->popupT('delete-tests', 'Usuwanie testu') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-tests', 'Czy na pewno chcesz usunąć wybrany test?') ?></p>
</div>

<div id="j_popup_delete_tests" title="<?php echo $this->popupT('delete-tests', 'Usuwanie testów') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-tests', 'Czy na pewno chcesz usunąć wybrane testy?') ?></p>
</div>

<?php echo $this->partial('partials/popups.phtml'); ?>

<script type="text/javascript">
/* <![CDATA[ */
  var popupYesNoName = ['delete_test', 'delete_tests'];
/* ]]> */
</script>