<div id="j_popup_delete_test" title="<?php echo $this->popupT('delete-test', 'Usuwanie testu z bazy') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-test', 'Czy na pewno chcesz usunąć test?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
  
  var popupYesNoName = 'delete_test';
/* ]]> */
</script>