<div id="j_popup_delete_bug_tracker" title="<?php echo $this->popupT('delete-bug-tracker', 'Usuwanie narzędzia') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-bug-tracker', 'Czy na pewno chcesz usunąć to narzędzie?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
  
  var popupYesNoName = 'delete_bug_tracker';
/* ]]> */
</script>