<div id="j_popup_delete_defect" title="<?php echo $this->popupT('delete-defects', 'Usuwanie zgłoszenia') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-defects', 'Czy na pewno chcesz usunąć wybrane zgłoszenie?') ?></p>
</div>

<div id="j_popup_delete_defects" title="<?php echo $this->popupT('delete-defects', 'Usuwanie zgłoszeń') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('delete-defects', 'Czy na pewno chcesz usunąć wybrane zgłoszenia?') ?></p>
</div>

<?php echo $this->partial('partials/popups.phtml'); ?>

<script type="text/javascript">
/* <![CDATA[ */  
  var popupYesNoName = ['delete_defect', 'delete_defects'];
/* ]]> */
</script>