<script type="text/javascript">
/* <![CDATA[ */
  language['ok'] = '<?php echo $this->generalT('Ok') ?>';
/* ]]> */
</script>

<div id="j_popup_field_is_empty" title="<?php echo $this->popupT('field-is-empty', 'Puste pole') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-alert"></span><?php echo $this->popupT('field-is-empty', 'Musisz uzupełnić pole.') ?></p>
</div>