<div id="j_popup_finish_project" title="<?php echo $this->popupT('finish-project', 'Zakończenie projektu') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('finish-project', 'Czy na pewno chcesz zakończyć projekt?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
  
  var popupYesNoName = 'finish_project';
/* ]]> */
</script>