<div id="j_popup_reset_user_password" title="<?php echo $this->popupT('reset-user-password', 'Wymuszenie zmiany hasła') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-trash"></span><?php echo $this->popupT('reset-user-password', 'Czy na pewno chcesz wymusić zmianę hasła?') ?></p>
</div>

<script type="text/javascript">
/* <![CDATA[ */
  language['yes'] = '<?php echo $this->generalT('Tak') ?>';
  language['no'] = '<?php echo $this->generalT('Nie') ?>';
  
  var popupYesNoName = 'reset_user_password';
/* ]]> */
</script>