<script type="text/javascript">
/* <![CDATA[ */
  language['ok'] = '<?php echo $this->generalT('Ok') ?>';
/* ]]> */
</script>

<div id="j_popup_select_least_one" title="<?php echo $this->popupT('select-least-one', 'Brak wybranych wierszy') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-alert"></span><?php echo $this->popupT('select-least-one', 'Musisz wybrać przynajmniej jeden wiersz.') ?></p>
</div>