<script type="text/javascript">
/* <![CDATA[ */
  language['ok'] = '<?php echo $this->generalT('Ok') ?>';
/* ]]> */
</script>

<div id="j_popup_select_least_one_checkbox" title="<?php echo $this->popupT('select-least-one-checkbox', 'Brak zaznaczonych pól wyboru') ?>" style="display: none;">
	<p><span style="float:left; margin:0 7px 20px 0;" class="ui-icon ui-icon-alert"></span><?php echo $this->popupT('select-least-one-checkbox', 'Musisz zaznaczyć przynajmniej jedno pole wyboru.') ?></p>
</div>