<?php $this->filterRequestConditions($this->filterForm->getValues()) ?>

<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>  
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>  --> 
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <?php if ($this->activeProject->isActive()): ?>
    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <?php if ($this->accessReleaseManagement): ?> 
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array(), 'release_add')?>" ><?php echo $this->t('Dodaj wydanie') ?></a></li>
        <?php endif; ?>
      </ul>
    </nav>
    <?php endif; ?>

    <form class="filterBox" name="<?php echo $this->filterForm->getName() ?>" method="<?php echo $this->filterForm->getMethod() ?>" action="<?php echo $this->filterForm->getAction() ?>">
      <?php echo $this->filterForm->filterAction->renderViewHelper() ?>
    
      <div class="search_text">
        <div class="filter">
          <div><?php echo $this->formLabel('search', $this->generalT('Szukaj')) ?></div>
          <div class="search_in_filter"><?php echo $this->filterForm->search->renderViewHelper() ?><a href="#" id="j_searchButton" class="icon_search icon-20"></a></div>
        </div>
      </div>
      <div class="search_filter">
        <div class="filter">
          <div><?php echo $this->formLabel('resultCountPerPage', $this->generalT('Wyniki')) ?></div>
          <div class="custom-select-xsmall"><?php echo $this->filterForm->resultCountPerPage->renderViewHelper() ?></div>
        </div>

        <?php echo $this->partial('partials/filter-buttons.phtml'); ?>
      </div>
    </form>

    <?php if (count($this->releases) > 0): ?>

    <table>
      <thead>
        <tr>
          <th><?php echo $this->sortingControl('Nazwa', 'release_name', 'sorting.phtml', $this->request) ?></th>
          <th><?php echo $this->sortingControl('Data rozpoczęcia', 'release_start_date', 'sorting.phtml', $this->request) ?></th>
          <th><?php echo $this->sortingControl('Data zakończenia', 'release_end_date', 'sorting.phtml', $this->request) ?></th>
          <th><?php echo $this->sortingControl('Liczba zadań', 'release_taskCount', 'sorting.phtml', $this->request) ?></th>
          <th><?php echo $this->sortingControl('Liczba defektów', 'release_defectCount', 'sorting.phtml', $this->request) ?></th>
          <th class="action_list_th"><?php echo $this->t('Akcje') ?></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->releases as $release): ?>
        <tr class="date_status_<?php echo $this->tagByDateRange($release) ?>">
          <td>
            <?php if ($release->isActive()): ?><span class="icon_star icon-20" style="color: #E0A025;"></span><?php endif;?>
            <a href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_view') ?>"><?php echo $this->escapeQuotes($release->getName()) ?></a>
          </td>
          <td class="t_date"><?php echo $release->getStartDate() ?></td>
          <td class="t_date"><?php echo $release->getEndDate() ?></td>
          <td class="t_number">
            <a href="<?php echo $this->projectUrl(array(), 'task_list').'?skipSavedFilter&release='.$release->getId() ?>">
              <?php echo $release->getExtraData('taskCount') ?>
            </a>
          </td>
          <td class="t_number">
            <?php if ($this->activeProject->getBugTracker()->getBugTrackerTypeId() == Application_Model_BugTrackerType::INTERNAL): ?>
              <a href="<?php echo $this->projectUrl(array(), 'defect_list').'?skipSavedFilter&release='.$release->getId() ?>">
                <?php echo $release->getExtraData('defectCount') ?>
              </a>
            <?php else: ?>
              <?php echo $release->getExtraData('defectCount') ?>
            <?php endif; ?>
          </td>
          <td>
            <?php if (($this->activeProject->isActive() && $this->accessReleaseManagement)
                      || $this->accessReportGenerate): ?>  
              <nav>
                <ul class="action_list">
                  <div class="popbox">
                    <a href="#" id="action_icon" class="open icon_cog icon-20"></a>
                    <div class='collapse'>
                      <ul class="box">
                        <?php if ($this->activeProject->isActive() && $this->accessReleaseManagement): ?>
                          <li><a href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_edit') ?>"><?php echo $this->t('Edytuj') ?></a></li>
                          <li><a href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_clone_multiform') ?>"><?php echo $this->t('Klonuj') ?></a></li>
                          <?php if ($release->isActive()): ?>
                            <li><a href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_deactivate') ?>"><?php echo $this->t('Dezaktywuj') ?></a></li>
                          <?php else: ?>
                            <li><a href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_activate') ?>"><?php echo $this->t('Aktywuj') ?></a></li>
                          <?php endif; ?>
                          <?php if ($release->getExtraData('taskCount') == 0): ?>
                            <li><a class="j_delete_release" href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_delete') ?>"><?php echo $this->t('Usuń') ?></a></li>
                          <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($this->accessReportGenerate): ?>
                          <li><a href="<?php echo $this->projectUrl(array('id' => $release->getId()), 'release_report') ?>"><?php echo $this->t('Raport') ?></a></li>
                        <?php endif; ?>  
                      </ul> 
                    </div>
                  </div>                
                </ul>
              </nav>
            <?php endif; ?>   
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-filter.phtml', $this->request->getParams()); ?>

    <?php else: ?>
    <div class="empty-text"><?php echo $this->t('Brak wydań') ?></div>
    <?php endif; ?>
    
  </article>    
</section>

<?php echo $this->partial('popups/delete-release.phtml'); ?>
<script type="text/javascript">
/* <![CDATA[ */
  var filterDefaultValues = <?php echo $this->filterForm->getDefaultValues(); ?>;
  var filterSavedValues = <?php echo $this->filterForm->getSavedValues(); ?>;
/* ]]> */
</script>
