<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Wydania') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div> -->  
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <?php if ($this->activeProject->isActive() && $this->accessReleaseAndPhaseManagement): ?>
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array('id' => $this->release->getId()), 'release_edit') ?>"><?php echo $this->t('Edytuj') ?></a></li>
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array('id' => $this->release->getId()), 'release_clone') ?>"><?php echo $this->t('Klonuj') ?></a></li>
          <?php if ($this->release->getExtraData('taskCount') == 0): ?>
            <li class="button_link_li"><a class="j_delete_release button_link" href="<?php echo $this->url(array('projectId' => $this->activeProject->getId(), 'id' => $this->release->getId()), 'release_delete') ?>"><?php echo $this->t('Usuń') ?></a></li>
          <?php endif; ?>
        <?php endif; ?>
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array(), 'phase_list').'?release='.$this->release->getId() ?>"><?php echo $this->t('Fazy') ?></a></li>
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array(), 'task_list').'?release='.$this->release->getId() ?>"><?php echo $this->t('Zadania') ?></a></li>
      </ul>
    </nav>

    
    <div class="textLabelEditor">
      <div id="text" class="content_label_title">
        <?php echo $this->escapeQuotes($this->release->getName()) ?>
        <?php if ($this->release->getEndDate(true) < time()): ?>
        <span class="isEnded"><?php echo $this->t('Zakończone') ?></span>
        <?php endif; ?>
      </div>
    </div>     
    <div class="contentLRtable">
      <div class="contentProperties_left">
        <div class="box_number_info">
            <a class="number_content" href="<?php echo $this->url(array(), 'task_list').'?release='.$this->release->getId() ?>"><?php echo $this->escapeQuotes($this->release->getExtraData('taskCount')) ?></a>
          <div class="descr_number_info"><?php echo $this->t('Liczba zadań') ?></div>
        </div>
        <div>
            <h5 class="break_page"><span aria-hidden="true" class="icon_pencil icon-20"></span><?php echo $this->t('Opis') ?></h5>
            <div><?php echo $this->escapeQuotes($this->release->getDescription()) ?></div>
        </div>
      </div>
      <div class="contentEditUser_right">        
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><?php echo $this->t('Data rozpoczęcia') ?></div>
          <div id="text" class="content_label"><?php echo $this->release->getStartDate() ?></div>
        </div>
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><?php echo $this->t('Data zakończenia') ?></div>
          <div id="text" class="content_label"><?php echo $this->release->getEndDate() ?></div>
        </div>
      </div>
     </div>
    
  </article>    
</section>

<?php echo $this->partial('popups/delete-release.phtml');