<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Wydania') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div> -->  
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->backUrl ?>"><?php echo $this->generalT('Powrót') ?></a></li>
        <?php if ($this->activeProject->isActive() && $this->accessReleaseManagement): ?>
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->release->getId()), 'release_edit') ?>"><?php echo $this->t('Edytuj') ?></a></li>
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->release->getId()), 'release_clone_multiform') ?>"><?php echo $this->t('Klonuj') ?></a></li>
          <?php if ($this->release->isActive()): ?>
            <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->release->getId()), 'release_deactivate') ?>"><?php echo $this->t('Dezaktywuj') ?></a></li>
          <?php else: ?>
            <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->release->getId()), 'release_activate') ?>"><?php echo $this->t('Aktywuj') ?></a></li>
          <?php endif; ?>
          <?php if ($this->release->getExtraData('taskCount') == 0): ?>
            <li class="button_link_li"><a class="j_delete_release button_link" href="<?php echo $this->projectUrl(array('id' => $this->release->getId()), 'release_delete') ?>"><?php echo $this->t('Usuń') ?></a></li>
          <?php endif; ?>
        <?php endif; ?>
        <?php if ($this->accessReportGenerate): ?>
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->release->getId()), 'release_report') ?>"><?php echo $this->t('Raport') ?></a></li>
        <?php endif; ?>
      </ul>
    </nav>
    
    <div class="textLabelEditor">
      <div id="text" class="content_label_title">
        <?php echo $this->escapeQuotes($this->release->getName()) ?>
        <?php if ($this->release->getEndDate(true) < time()): ?>
        <span class="isEnded"><?php echo $this->t('Zakończone') ?></span>
        <?php endif; ?>
      </div>
    </div>    
    
    <div class="contentLRtable">
      
      <div class="contentProperties_left">
        <div class="box_number_info">
            <a class="number_content" href="<?php echo $this->projectUrl(array(), 'task_list').'?skipSavedFilter&release='.$this->release->getId() ?>">
              <?php echo $this->escapeQuotes($this->release->getExtraData('taskCount')) ?>
            </a>
          <div class="descr_number_info"><?php echo $this->t('Liczba zadań') ?></div>
        </div>         
        
        <?php if ($this->activeProject->getBugTracker()->getBugTrackerTypeId() == Application_Model_BugTrackerType::INTERNAL): ?>
        <div class="box_number_info">
            <a class="number_content" href="<?php echo $this->projectUrl(array(), 'defect_list').'?skipSavedFilter&release='.$this->release->getId() ?>">
              <?php echo $this->escapeQuotes($this->release->getExtraData('defectCount')) ?>
            </a>
          <div class="descr_number_info"><?php echo $this->t('Liczba defektów') ?></div>
        </div>
        <?php endif; ?>
      </div>
      
      <div class="contentEditUser_right">        
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><?php echo $this->t('Data rozpoczęcia') ?></div>
          <div id="text" class="content_label"><?php echo $this->release->getStartDate() ?></div>
        </div>
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><?php echo $this->t('Data zakończenia') ?></div>
          <div id="text" class="content_label"><?php echo $this->release->getEndDate() ?></div>
        </div>       
        <div class="textLabelEditor">
          <div class="textLabelEditor_text"><?php echo $this->t('Opis') ?></div>
          <div id="text" class="content_label"><?php echo nl2br($this->release->getDescription()) ?></div>
        </div>
      </div>
      
    </div>
    
  </article>    
</section>

<?php echo $this->partial('popups/delete-release.phtml');