<section id="content">
 <!-- <div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Zadania') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>  -->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
      <div><?php echo $this->form->backUrl->renderViewHelper() ?></div>
          
        <div class="formContainer full">
          <span>
            <?php echo $this->form->title->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('title', $this->t('Tytuł')) ?>
            <?php foreach ($this->form->getErrors('title') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('title')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('title')->getValidator('StringLength')->getMax()
              )) ?></div>
          <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer full">
          <span>
            <?php echo $this->form->description->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('description', $this->t('Opis')) ?>
            <?php foreach ($this->form->getErrors('description') as $error): ?>
                <div class="error_msg"><?php echo $this->errorT($error, array(
                  'min' => $this->form->getElement('description')->getValidator('StringLengthOneCharacterLineBreaks')->getMin(),
                  'max' => $this->form->getElement('description')->getValidator('StringLengthOneCharacterLineBreaks')->getMax()
                )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <?php echo $this->form->releaseName->renderViewHelper() ?>
            <div><?php echo $this->form->releaseId->renderViewHelper() ?></div>
            <?php echo $this->formLabel('releaseName', $this->t('Wydanie')) ?>
            <?php foreach ($this->form->getErrors('releaseId') as $error): ?>            
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->environments->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('environments', $this->t('Środowiska')) ?>
            <?php foreach ($this->form->getErrors('environments') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->versions->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('versions', $this->t('Wersje')) ?>
            <?php foreach ($this->form->getErrors('versions') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <div><?php echo $this->form->priority->renderViewHelper() ?></div>
            <?php echo $this->formRequiredLabel('priority', $this->t('Priorytet')); ?>
            <?php foreach ($this->form->getErrors('priority') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div> 

        <div class="formContainer">
          <span>
            <?php echo $this->form->dueDate->renderViewHelper() ?><span class="calendar_icon"></span>
            <?php echo $this->formRequiredLabel('dueDate', $this->t('Termin realizacji')) ?>
            <?php foreach ($this->form->getErrors('dueDate') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min'     => $this->form->getMinDate(),
                'max'     => $this->form->getMaxDate(),
                'format'  => 'RRRR-MM-DD',
                'date'    => $this->form->getMinDate()
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <div><?php echo $this->form->assigneeName->renderViewHelper() ?></div>
            <div><?php echo $this->form->assigneeId->renderViewHelper() ?></div>
            <?php echo $this->formRequiredLabel('assigneeName', $this->t('Przypisz do')) ?><span><a id="j_assignToMe" href="#"><?php echo $this->t('Przypisz do mnie') ?></a></span>
            <?php foreach ($this->form->getErrors('assigneeId') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer full">
          <span>
            <?php echo $this->form->tags->renderViewHelper() ?>
            <?php echo $this->formLabel('tags', $this->t('Tagi')) ?>
            <?php foreach ($this->form->getErrors('tags') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
        
        <?php echo $this->partial('partials/attachments-form.phtml', array('form' => $this->form)); ?>

        <div>
          <span id="save"><?php echo $this->formSubmit('save', $this->t('Zapisz')) ?></span>
          <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
        </div>
        <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>  

        <div>
          <?php echo $this->form->csrf->renderViewHelper() ?>
          <?php foreach ($this->form->getErrors('csrf') as $error): ?>
          <div><?php echo $this->errorT($error) ?></div>
          <?php endforeach; ?>
        </div>

     
    </form>
  </article>
</section>

<script type="text/javascript">
/* <![CDATA[ */
  language.charactersLeft = '<?php echo $this->generalT('Pozostało __left__/__max__ znaków.') ?>';
  var currentUser = {id: <?php echo $this->authUser->getId() ?>, name: '<?php echo $this->authUser->getFullname().' ('.$this->authUser->getEmail().')' ?>'};
  
  var autocompleteData = {
    url: '<?php echo $this->projectUrl(array(), 'project_user_list_ajax') ?>',
    textInputName: '#assigneeName',
    dstName: '#assigneeId'
  };
  
  <?php if ($this->form->getMinDate() !== null): ?>
    var minDate = '<?php echo $this->form->getMinDate() ?>';
  <?php endif; ?>
    
  <?php if ($this->form->getMaxDate() !== null): ?>
    var maxDate = '<?php echo $this->form->getMaxDate() ?>';
  <?php endif; ?>
  
  <?php if (isset($this->prePopulatedEnvironments)) :?>
    prePopulated['environments'] = <?php echo $this->prePopulatedEnvironments?>;
  <?php endif?>

  <?php if (isset($this->prePopulatedVersions)) :?>
    prePopulated['versions'] = <?php echo $this->prePopulatedVersions?>;
  <?php endif?>

  <?php if (isset($this->prePopulatedTags)) :?>
    prePopulated['tags'] = <?php echo $this->prePopulatedTags?>;
  <?php endif?>
  
  url.environmentListAjax = '<?php echo $this->projectUrl(array(), 'environment_list_ajax') ?>';
  url.versionListAjax = '<?php echo $this->projectUrl(array(), 'version_list_ajax') ?>';
  url.tagListAjax = '<?php echo $this->projectUrl(array(), 'tag_list_ajax') ?>';
  
  var autocompleteRelease = {
    url: '<?php echo $this->projectUrl(array(), 'release_list_for_forward_ajax') ?>',
    textInputName: '#releaseName',
    dstName: '#releaseId'
  };
/* ]]> */
</script>