<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Zadania') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->  
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>
    <h3><?php echo $this->task->getObjectNumber() ?> <?php echo $this->task->getTitle() ?></h3>

    <form name="j_endTaskRunForm" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
      <?php echo $this->form->backUrl->renderViewHelper() ?>
        <div class="formContainer">
          <span>
            <div><?php echo $this->form->assigneeName->renderViewHelper() ?></div>
            <div><?php echo $this->form->assigneeId->renderViewHelper() ?></div>
            <?php echo $this->formRequiredLabel('assigneeName', $this->t('Przypisz do')) ?><span><a id="j_assignToMe" href="#"><?php echo $this->t('Przypisz do mnie') ?></a></span>
            <?php foreach ($this->form->getErrors('assigneeId') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
        
        <div class="formContainer full">
          <span>
            <?php echo $this->form->comment->renderViewHelper() ?>
            <?php echo $this->formLabel('comment', $this->t('Komentarz')) ?>
            <?php foreach ($this->form->getErrors('comment') as $error): ?>
                <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('title')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('title')->getValidator('StringLength')->getMax()
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div>
          <span id="save"><?php echo $this->formSubmit('reopen', $this->t('Otwórz ponownie')) ?></span>
          <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
        </div>
        <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>

        <div>
          <?php echo $this->form->csrf->renderViewHelper() ?>
          <?php foreach ($this->form->getErrors('csrf') as $error): ?>
          <div><?php echo $this->errorT($error) ?></div>
          <?php endforeach; ?>
        </div>

     
    </form>
  </article>
</section>

<script type="text/javascript">
/* <![CDATA[ */
  var currentUser = {id: <?php echo $this->authUser->getId() ?>, name: '<?php echo $this->authUser->getFullname().' ('.$this->authUser->getEmail().')' ?>'};
  language.charactersLeft = '<?php echo $this->generalT('Pozostało __left__/__max__ znaków.') ?>';
  
  var autocompleteData = {
    url: '<?php echo $this->projectUrl(array(), 'project_user_list_ajax') ?>',
    textInputName: '#assigneeName',
    dstName: '#assigneeId'
  };
/* ]]> */
</script>