<?php $this->filterRequestConditions($this->filterForm->getValues()) ?>

<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i> 
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>  -->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array(), 'admin_role_add')?>" ><?php echo $this->t('Dodaj rolę') ?></a></li>
      </ul>
    </nav>

    <form class="filterBox" name="<?php echo $this->filterForm->getName() ?>" method="<?php echo $this->filterForm->getMethod() ?>" action="<?php echo $this->filterForm->getAction() ?>">

      <div class="search_text">
        <div class="filter">
          <div><?php echo $this->formLabel('search', $this->t('Szukaj')) ?></div>
          <div class="search_in_filter"><?php echo $this->filterForm->search->renderViewHelper() ?><a href="#" id="j_searchButton" class="icon_search icon-20"></a></div>
        </div>
      </div>

      <div class="search_filter">
        <div class="filter">
          <div><?php echo $this->formLabel('project', $this->t('Projekt')) ?></div>
          <div class="custom-select-xsmall"><?php echo $this->filterForm->project->renderViewHelper() ?></div>
        </div>

        <div class="filter">
          <div><?php echo $this->formLabel('resultCountPerPage', $this->t('Wyniki')) ?></div>
          <div class="custom-select-xsmall"><?php echo $this->filterForm->resultCountPerPage->renderViewHelper() ?></div>
        </div>

        <div class="filterButton"><?php echo $this->formButton('j_filterButton', $this->t('Filtruj')) ?></div>
      </div>
    </form>
    
    <?php if (count($this->roles) > 0): ?>
    
      <table>
        <thead>
          <tr>
            <th><?php echo $this->sortingControl('Nazwa', 'role_name', 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->sortingControl('Projekt', $this->createSortedFieldName('role', 'name', array('project')), 'sorting.phtml', $this->request) ?></th>
            <th class="action_list_th"><?php echo $this->t('Akcje') ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->roles as $role): ?>
          <tr>
            <td><?php echo $this->escapeQuotes($role->getName()) ?></td>
            <td class="t_name" style="width: 500px; max-width: 500px"><?php echo $this->escapeQuotes($role->getProject()->getName()) ?></td>
            <td>
              <?php if ($role->getProject()->getStatusId() != Application_Model_ProjectStatus::FINISHED): ?>
                <nav>
                  <ul class="action_list">
                    <div class="popbox">
                      <a href="#" id="action_icon" class="open icon_cog icon-20"></a>
                      <div class='collapse'>
                        <ul class="box">
                            <li><a href="<?php echo $this->url(array('id' => $role->getId()), 'admin_role_edit')?>"><?php echo $this->t('Edytuj') ?></a></li>
                            <li><a class="j_delete_role" href="<?php echo $this->url(array('id' => $role->getId()), 'admin_role_delete')?>"><?php echo $this->t('Usuń') ?></a></li>
                        </ul> 
                      </div>
                    </div>                  
                  </ul>
                </nav>
              <?php endif; ?>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-filter.phtml', $this->request->getParams()); ?>
    
    <?php else: ?>
      <div class="empty-text"><?php echo $this->t('Brak ról') ?></div>
    <?php endif; ?>

  </article>    
</section>

<?php echo $this->partial('popups/delete-role.phtml');