<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->emailT($this->name, 'subject') ?></title>
</head>
<body>
  <div>
    <h5 style="font-size: 12px"><?php echo $this->emailT($this->name, 'Witaj NAME!', array('name' => $this->user->getFullname())) ?></h5>
    <p><?php echo $this->emailT($this->name, 'Zgłosiłeś chęć zmiany hasła dostępu do serwisu. Aby aktywować nowe hasło, kliknij w poniższy link.') ?></p>

    <p><a href="<?php echo $this->url(array('uid' => base64_encode($this->user->getEmail()), 'code' => $this->user->getToken()), 'user_new_password') ?>"><?php echo $this->url(array('uid' => base64_encode($this->user->getEmail()), 'code' => $this->user->getToken()), 'user_new_password') ?></a></p>

    <p>
      <?php echo $this->emailT($this->name, 'Jeżeli nie chciałeś zmienić hasła, prosimy o zignorowanie tej wiadomości.') ?>
      <br />
      <?php echo $this->emailT($this->name, 'W razie jakichkolwiek pytań lub wątpliwości zapraszamy do KONTAKTU.', array(
        'email' => Zend_Registry::get('config')->contact->email
      )) ?>
    </p>
    <p><?php echo $this->emailT($this->name, 'Pozdrawiamy') ?></p>
  </div>

</body>
</html>
</html>