<section id="content">
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <table>
      <thead>
        <tr>
          <th><?php echo $this->t('Priorytet zadania') ?></th>
          <th><?php echo $this->t('Wszystkie zadania') ?></th>
          <th><?php echo $this->t('Zadania niewykonane') ?></th>
          <th><?php echo $this->t('Zadania zakończone') ?></th>
          <th><?php echo $this->t('Zadania zakończone powodzeniem') ?></th>
          <th><?php echo $this->t('Zadania zakończone niepowodzeniem') ?></th>
          <th><?php echo $this->t('Zadania w toku') ?></th>
          <th><?php echo $this->t('Zadania zawieszone') ?></th>
          <th style="width: 200px;"><?php echo $this->t('Postęp') ?> [%]</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->taskRuns as $taskRun): ?>
        <tr>
          <td><?php echo $this->typeT($taskRun->getPriority(), 'TASK_RUN_PRIORITY') ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('allTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('openTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('closedTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('successTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('failedTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('inProgressTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($taskRun->getExtraData('suspendedTasks')) ?></td>
          <td>
            <?php echo $this->escapeQuotes($this->percent($taskRun->getExtraData('allTasks'), $taskRun->getExtraData('closedTasks'))) ?>
            <?php if ($taskRun->getExtraData('allTasks') > 0) { echo $this->partial('partials/tasks-percent-stripe.phtml', $taskRun->getAllExtraData()); } ?>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    
    <div class="button_edit"><a href="<?php echo $this->url(array(), 'report_export_all_task_run_statuses_by_priority') ?>"><?php echo $this->generalT('Eksportuj wszystko') ?></a></div>
    
  </article>    
</section>