<div id="mainContentS">
  <article class="staticContent">
    <h1 style="margin: 20px 0px 40px;"><img src="<?php echo $this->baseUrl('/img/edu_logo_black.png') ?>"> </h1>

    <p><?php echo $this->t('Part1') ?></p>
    <p><?php echo $this->t('Part2') ?></p>
    <div class="about_nav_big_icon">
      <a href="#about_first" title="Trener" alt="Trener"><span class="icon-user4 icon-Bigger" aria-hidden="true"></span></a><a href="#about_second" title="Materiały" alt="Materiały"><span class="icon-file2 icon-Bigger" aria-hidden="true"></span></a><a href="#about_third" title="Powiadomienia" alt="Powiadomienia"><span class="icon-bell icon-Bigger" aria-hidden="true"></span></a>
    </div>
    <p><?php echo $this->t('Part3') ?></p>
    <p class="kursywa"><?php echo $this->t('Part4') ?></p>
    <div id="about_first" class="about_big_icon">
      <span class="icon-user4 icon-Bigger" aria-hidden="true"></span>
    </div>
    <p>* * * * * * *</p>
    <p><?php echo $this->t('Part5') ?></p>
    <p class="kursywa"><?php echo $this->t('Part6') ?></p>
    <div id="about_second" class="about_big_icon">
      <span class="icon-file2 icon-Bigger" aria-hidden="true"></span>
    </div>
    <p>* * * * * * *</p>
    <p><?php echo $this->t('Part7') ?></p>
    <p><?php echo $this->t('Part8') ?></p>
    <p><?php echo $this->t('Part9') ?></p>
    <p><?php echo $this->t('Part10') ?></p>
    <p class="kursywa"><?php echo $this->t('Part11') ?></p>
    <div id="about_third" class="about_big_icon">
      <span class="icon-bell icon-Bigger" aria-hidden="true"></span>
    </div>
    <p>* * * * * * *</p>
    <p><?php echo $this->t('Part12') ?></p>
    <p><?php echo $this->t('Part13') ?></p> 
    <p><?php echo $this->t('Masz pytania dotyczące funkcjonowania Edu? NAPISZ DO NAS.', array('url' => $this->url(array(), 'contact'))) ?></p>
    
  </article>
</div>

