<section id="content">
  <article class="article_in_content full">
    <h1 class="content_title">Terms of use TestArena</h1>

      <h3>Welcome in TestArena!</h3>                       
      <p>The following Terms of service ("Terms of service") specifies the terms of use terms ("Terms") of the TestArena.pl website ("TestArena", "TestArena.pl", "Website", "Site", "Services").</p>                        
      <p>TestArena.pl is a property and thus managed by <a class="j_new_window" href="http://21cn.pl" title="21cn">21CN</a> ("We"). Terms of service states a legal agreement ("Agreement") between a User ("User", "You") and We from the moment the User accepts this Terms of service. You can print and keep a copy of this document.</p>                       
      <p>All resolutions stated by this Terms of service document apply both to registered users and guests visiting the Website. If you do not agree with the Terms of this document, we request you to to leave the Website and cease any use of the Website.</p>
      <p>In case of any uncertainities with the Terms of Service document we advise you to contact Us at <a href="mailto:<?php echo $this->supportEmail ?>"><?php echo $this->supportEmail ?></a></p>

      <h3>User account</h3>                       
      <p>By creating a user account on the Website or by using the accessible Administrator account You become fully responsible for the content of this Website and all activities related to Your account. You are also responsible for keeping your password and login information safe.</p>                        
      <p>By selecting a Username you agree that it is not offensive, disrespectful, obscenic or harmful to other Users in any way.</p>
      <p>Creating a User account and using the TestArena website is free of any charge.</p>

      <h3>User responisbilities</h3>                        
      <p>When using the Website you ensure Us and the whole TestArena community that you will use it in a respectful manner.</p>
      <p>We reserve the right to remove any content which is in contradiction with Terms of Service, breaks the rules and regulations in force, contains information that breaks the law, is brutal, disrespectful, harmful or violites the intelectual property of third party people in any other way.</p>
      <p>A User is obliged to use the Website in a way that does not directly affect the content posted by other Users. Based on the fact that the Administrator account is avaible to all, We forbid Users to modify or remove content posted by other Users.</p>
      
      <h3>Responsibilities of the people that use TestArena</h3>                       
      <p>TestArena is not able to verify all the content posted by its Users, and thus We cannot guarantee that all of the content contained within the Website is viable and accurate.</p>                        
      <p>There is a possibility that when browsing the Website You will encounter the content that you might find offensive, harmful or inapropriate in any way.</p>
      <p>We renounce responsibility for any harm that might come from the Service being used in an inappropriate way.</p>
      
      <h3>The content of TestArena.pl</h3>                        
      <p>Except the content posted by Users, all content of TestArena is the property of TestArena.pl and its liscense holders and thus it is protected by the international copyright laws.</p>
      <p>The entirety of the Website, and each of its elements cannot be copied, sold or used in any other way whithout a written consent from TestArena.pl.</p>

      <h3>Guarantees and disclaimers</h3>
      <p>TestArena was created with the utmost care. Nevertheless we cannot guarantee that its content is whithout any mistakes and with accuracy. We do not take any responsibility for the direct or indirect damage that the usage of the Website may cause, unless it was caused by Our intended action or a major ommision on Our side.</p>
      <p>TestArena reserves the right to remove User content when updating the Website. The Service does not guarantee the preservation of User data even whithout an update being the cause.</p>

      <h3>Trademarks of TestArena.pl</h3>
      <p>Unless a specificic information states otherwise, all trademarks on the Website are reserved and protected by copyright laws. This applies especially to the TestArena.pl logo and emblems. Trademarks and graphical elements located on the Website are all intelectual properties of TestArena.pl.</p>

      <h3>Final provisions</h3>
      <p>This Terms of service comes into force on January 7th, 2013. TestArena reserves the right to change this Terms of Service document about which it will inform its Users.</p>

  </article>    
</section>