<section id="content">
  <article class="article_in_content full">
    <h1 class="content_title">Warunki korzystania z serwisu TestArena</h1>

      <h3>Witamy w TestArena!</h3>                       
      <p>Niniejszy regulamin ("Regulamin") określa warunki ("Warunki") korzystania z serwisu TestArena.pl ("TestArena", " TestArena.pl", "Serwis", "Strona").    </p>                        
      <p>TestArena.pl stanowi własność i jest zarządzany przez <a class="j_new_window" href="http://21cn.pl" title="21cn">21CN</a> ("My"). Regulamin stanowi legalną umowę ("Umowa") zawieraną pomiędzy Użytkownikiem a Nami w chwili akceptacji Regulaminu. Możesz wydrukować i zachować kopię niniejszego Regulaminu. </p>                       
      <p>Wszystkie postanowienia ujęte w Regulaminie dotyczą zarówno zarejestrowanych użytkowników, jak i osoby odwiedzające Serwis. Jeżeli nie zgadzasz się z przedstawionymi Warunkami, prosimy o opuszczenie Serwisu i zaprzestanie korzystania z jego usług ("Usługi").</p>
      <p>W razie jakichkolwiek niejasności związanych z treścią Regulaminu prosimy o kontakt mailowy na adres <a href="mailto:<?php echo $this->supportEmail ?>"><?php echo $this->supportEmail ?></a></p>

      <h3>Konto użytkownika</h3>                       
      <p>Tworząc konto Użytkownika na Stronie lub korzystając z ogólnodostępnego konta administratora stajesz się w pełni odpowiedzialny/odpowiedzialna za wszelkie treści umieszczane przez Ciebie na Stronie oraz wszystkie aktywności związane z Twoim kontem. Twoim obowiązkiem jest również dbanie o prawidłowe zabezpieczenie hasła dostępu do swojego konta.   </p>                        
      <p>Wybierając nazwę Użytkownika potwierdzasz, że nie jest to nazwa obraźliwa, obsceniczna lub w jakikolwiek sposób napastliwa wobec innych Użytkowników.</p>
      <p>Założenie konta i korzystanie z Serwisu TestArena.pl jest zupełnie bezpłatne.</p>

      <h3>Odpowiedzialność Użytkownika</h3>                        
      <p>Korzystając ze Strony zapewniasz Nas i całą wspólnotę skupioną wokół TestArena, że będziesz korzystać z Serwisu w sposób właściwy i z szacunkiem wobec pozostałych Użytkowników.</p>
      <p>Zastrzegamy sobie prawo do usunięcia treści, które naruszają postanowienia Regulaminu, łamią obowiązujące prawa i przepisy, zawierają informacje niezgodne z prawem, brutalne, obraźliwe, szkodliwe lub w inny sposób nieodpowiednie oraz naruszają prawa własności intelektualnej osób trzecich.</p>
      <p>Użytkownik jest zobowiązany do korzystania z Serwisu w taki sposób aby nie wpływać bezpośrednio na dane zamieszczone przez innych. Ze względu na ogólną dostępność do konta administratora zabrania się modyfikacji oraz usuwania treści zamieszczonych przez innych Użytkowników.</p>
      
      <h3>Odpowiedzialność wobec osób korzystających z TestArena</h3>                       
      <p>TestArena nie jest w stanie zweryfikować wszystkich treści zamieszczonych przez Użytkowników, dlatego też nie możemy zagwarantować pełnej wiarygodności i dokładności materiału znajdującego się w Serwisie.</p>                        
      <p>Istnieje ryzyko, że przeglądając TestArena natkniesz się na treści, które uznasz za obraźliwe, krzywdzące lub w inny sposób niepoprawne. </p>
      <p>Zrzekamy się odpowiedzialności za jakiekolwiek szkody, straty oraz zniszczenia spowodowane niewłaściwym używaniem Serwisu.</p>
      
      <h3>Zawartość TestArena.pl</h3>                        
      <p>Za wyjątkiem treści umieszczanych przez Użytkowników, cała zawartość Strony jest własnością TestArena.pl oraz jego licencjodawców i jest chroniona międzynarodowym prawem autorskim.</p>
      <p>Zarówno cała Strona, jak i jakakolwiek jej część nie mogą być powielane, kopiowane, sprzedawane, odsprzedawane lub w jakikolwiek inny sposób wykorzystywane bez pisemnej zgody TestArena.pl.</p>

      <h3>Gwarancje i wyłączenia odpowiedzialności</h3>
      <p>TestArena.pl został przygotowany z najwyższą starannością. Mimo to nie możemy zagwarantować całkowitej bezbłędności i dokładności prezentowanych treści. Wykluczamy wszelkie roszczenia z tytułu odpowiedzialności za szkody bezpośrednie lub pośrednie wynikające z korzystania z Serwisu, o ile nie są one wynikiem zamierzonego działania lub poważnego zaniedbania z Naszej strony. </p>
      <p>TestArena zastrzega sobie możliwość usunięcia danych wprowadzonych przez Użytkowników podczas aktualizacji aplikacji. Serwis nie daje gwarancji utrzymania danych nawet w przypadku braku aktualizacji.</p>

      <h3>Znaki towarowe TestArena.pl</h3>
      <p>O ile nie umieszczono innej informacji, wszystkie znaki towarowe znajdujące się na Stronie są zastrzeżone. Dotyczy to w szczególności marki TestArena.pl, firmowego logo i emblematów. Zamieszczone na Stronie marki oraz elementy kompozycyjne stanowią własność intelektualną TestArena.pl.</p>

      <h3>Postanowienia końcowe</h3>
      <p>Regulamin wchodzi w życie z dniem 07 stycznia 2013 roku. TestArena zastrzega sobie prawo do wprowadzania zmian do Regulaminu, o czym poinformuje swoich Użytkowników.</p>

  </article>    
</section>