<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Zadania') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->  
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>
    <h3><?php echo $this->taskTest->getTest()->getObjectNumber() ?> <?php echo $this->taskTest->getTest()->getName() ?></h3>
    <strong><?php echo $this->taskTest->getTask()->getObjectNumber() ?> <?php echo $this->taskTest->getTask()->getTitle() ?></strong>

    <form name="j_endTaskRunForm" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
      <?php echo $this->form->backUrl->renderViewHelper() ?>
      
        <div class="formContainer">
          <span>
            <?php echo $this->form->resolutionId->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('resolutionId', $this->t('Status rozwiązania')); ?>
            <?php foreach ($this->form->getErrors('resolutionId') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div> 
        
        <div class="formContainer full">
          <span>
            <?php echo $this->form->comment->renderViewHelper() ?>
            <?php echo $this->formLabel('comment', $this->t('Komentarz')) ?>
            <?php foreach ($this->form->getErrors('comment') as $error): ?>
                <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div>
          <span id="save"><?php echo $this->formSubmit('resolve', $this->t('Rozwiąż')) ?></span>
          <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
        </div>
        <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>

        <div>
          <?php echo $this->form->csrf->renderViewHelper() ?>
          <?php foreach ($this->form->getErrors('csrf') as $error): ?>
          <div><?php echo $this->errorT($error) ?></div>
          <?php endforeach; ?>
        </div>
        
    </form>
  </article>
</section>

<script type="text/javascript">
/* <![CDATA[ */
  language.charactersLeft = '<?php echo $this->generalT('Pozostało __left__/__max__ znaków.') ?>';
/* ]]> */
</script>