<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Zadania') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div> --> 
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
          <?php if ($this->taskTest->getResolutionId() !== null): ?>
            <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->taskTest->getId()), 'task_test_change')?>"><?php echo $this->t('Zmień status') ?></a></li>
          <?php else: ?>
            <li class="button_link_li"><a class="button_link" href="<?php echo $this->projectUrl(array('id' => $this->taskTest->getId()), 'task_test_resolve') ?>"><?php echo $this->t('Rozwiąż') ?></a></li>
          <?php endif; ?>
      </ul>
    </nav>

    <div class="textLabelEditor">
      <div id="text" class="content_label_title"><span class="object_nr"><?php echo $this->escapeQuotes($this->taskTest->getTest()->getObjectNumber()) ?></span> <?php echo $this->escapeQuotes($this->taskTest->getTest()->getName()) ?></div>
    </div>     
    
    <div class="contentLRtable">
      
      <div class="contentProperties_left">
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Status') ?>: </div>
          <div id="text" class="content_label">
            <?php if ($this->taskTest->getResolutionId() !== null): ?>
              <?php echo $this->showResolutionIcon($this->taskTest->getResolution()) ?><b><?php echo $this->taskTest->getResolution()->getName() ?></b>
            <?php else: ?>
              <b><?php echo $this->generalT('Nierozwiązany') ?></b>
            <?php endif; ?>
          </div>
        </div>
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Opis') ?>: </div>
          <div id="text" class="content_label"> <?php echo nl2br($this->escapeQuotes($this->taskTest->getTest()->getDescription())) ?></div>
        </div>
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Zadanie') ?>: </div>
          <div id="text" class="content_label"><a href="<?php echo $this->projectUrl(array('id' => $this->taskTest->getTask()->getId()), 'task_view') ?>"><span class="object_nr"><?php echo $this->escapeQuotes($this->taskTest->getTask()->getObjectNumber()) ?></span> <?php echo nl2br($this->escapeQuotes($this->taskTest->getTask()->getTitle())) ?></a></div>
        </div>
    
        <div>
          <h5 class="break_page"><span aria-hidden="true" class="icon_ul icon-20"></span><?php echo $this->t('Pozycje') ?></h5>
          <table>
            <thead>
              <tr>
                <th><?php echo $this->t('Treść') ?></th>
                <th><?php echo $this->t('Status') ?></th>
                <th class="action_list_th"><?php echo $this->t('Akcje') ?></th>
              </tr>
            </thead>
            <tbody>
            <?php foreach ($this->taskTest->getChecklistItems() as $taskChecklistItem): ?>
              <tr<?php echo $this->taskChecklistItemStatus($taskChecklistItem);?>>
                <td><?php echo $taskChecklistItem->getChecklistItem()->getName() ?></td>
                <td><?php echo $this->statusT($taskChecklistItem->getStatus(), 'TASK_CHECKLIST_ITEM') ?></td>
                <td>
                  <nav>
                    <ul class="action_list">
                      <div class="popbox">
                        <a href="#" id="action_icon" class="open icon_cog icon-20"></a>
                        <div class='collapse'>
                          <ul class="box">
                          <?php if ($taskChecklistItem->getStatusId() != Application_Model_TaskChecklistItemStatus::NONE): ?>
                            <li><a href="<?php echo $this->projectUrl(array('id' => $taskChecklistItem->getId()), 'task_checklist_item_change_status_to_none') ?>"><?php echo $this->statusT('NONE', 'TASK_CHECKLIST_ITEM') ?></a></li>
                            <li class="menuSeparator"></li>
                          <?php endif; ?>

                          <?php if ($taskChecklistItem->getStatusId() != Application_Model_TaskChecklistItemStatus::RESOLVE): ?>
                            <li><a href="<?php echo $this->projectUrl(array('id' => $taskChecklistItem->getId()), 'task_checklist_item_change_status_to_resolve') ?>"><?php echo $this->statusT('RESOLVE', 'TASK_CHECKLIST_ITEM') ?></a></li>
                          <?php endif; ?>

                          <?php if ($taskChecklistItem->getStatusId() != Application_Model_TaskChecklistItemStatus::UNRESOLVE): ?>
                            <li><a href="<?php echo $this->projectUrl(array('id' => $taskChecklistItem->getId()), 'task_checklist_item_change_status_to_unresolve') ?>"><?php echo $this->statusT('UNRESOLVE', 'TASK_CHECKLIST_ITEM') ?></a></li>
                          <?php endif; ?>
                          </ul> 
                        </div>
                      </div>                
                    </ul>
                  </nav>
                </td>
              </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        </div>
      </div>
      
      <div class="contentEditUser_right">
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Autor') ?>: </div>
          <div id="text" class="content_label"><?php echo $this->escapeQuotes($this->taskTest->getTest()->getAuthor()->getFullname()) ?></div>
        </div>
        <div class="textLabelPropertiesDiv" style="border-bottom:0px solid;">
          <div class="textLabelEditor_text"><?php echo $this->t('Data utworzenia') ?>: </div>
          <div id="text" class="content_label"> <?php echo $this->taskTest->getTest()->getCreateDate() ?></div>
        </div> 
        
        <?php echo $this->partial('partials/attachments.phtml', array('attachments' => $this->taskTest->getTest()->getExtraData('attachments'))); ?> 

        <?php echo $this->partial('comment/partial.phtml', array(
          'subjectId'     => $this->taskTest->getId(),
          'subjectType'   => Application_Model_CommentSubjectType::TASK_TEST,
          'addCommentOn'  => $this->activeProject->isActive()
        )); ?>
      </div>
      
    </div>
    
  </article>    
</section>
  
  