<script id="j_fullAttachmentObjectTmpl" type="text/x-jquery-tmpl">
<input id="attachmentIds-attachmentId_${id}" type="hidden" value="${id}" name="attachmentIds[attachmentId_${id}]" class="j_attachmentId">
<input id="attachmentNames-attachmentName_${id}" type="hidden" value="${name}" name="attachmentNames[attachmentName_${id}]" class="j_attachmentName">
<span class="fileElement"><span><span class="icon_link_alt icon-13" aria-hidden="true"></span> ${name}</span><a href="#" id="j_removeAttachmentButton_${id}" class="deleteFileElement j_removeAttachmentButton"><span class="icon_close icon-17" aria-hidden="true"></span></span></span>
</script>
<script id="j_attachmentBoxTmpl" type="text/x-jquery-tmpl" >
<span class="fileElement"><span><span class="icon_link_alt icon-13" aria-hidden="true"></span> ${name}</span><a href="#" id="j_removeAttachmentButton_${id}" class="deleteFileElement j_removeAttachmentButton"><span class="icon_close icon-17" aria-hidden="true"></span></span></span>
</script>