<script id="j_checklistItemTmpl" type="text/x-jquery-tmpl" >
<div id="j_checklistItem_${index}" class="j_checklistItem">
<input name="itemIds[itemId_${index}]" id="itemId_${index}" value="${id}" type="hidden">
<input name="itemNames[itemName_${index}]" id="itemName_${index}" class="j_checklistItemName" value="${name}" maxlength="255" type="text">
<a href="#" id="j_removeChecklistItemButton_${index}" class="j_removeChecklistItemButton"><span class="icon_close icon-17" aria-hidden="true"></a>
</div>
</script>