<div style="display: block; margin-top: 5px;">
  <div class="filterButton" title="<?php echo $this->generalT('Filtruj - opis'); ?>">
    <?php echo $this->formButton('j_filterButton', $this->generalT('Filtruj')) ?>
  </div>
  <div class="filterButton" title="<?php echo $this->generalT('Filtruj i zapisz - opis'); ?>">
    <?php echo $this->formButton('j_filterAndSaveButton', $this->generalT('Filtruj i zapisz')) ?>
  </div>
  <div class="filterButton" title="<?php echo $this->generalT('Przywróć - opis'); ?>">
    <?php echo $this->formButton('j_restoreButton', $this->generalT('Przywróć')) ?>
  </div>
  <div class="filterButton" title="<?php echo $this->generalT('Wyczyść - opis'); ?>">
    <?php echo $this->formButton('j_clearButton', $this->generalT('Wyczyść')) ?>
  </div>
</div>
