<div id="j_defectContent">
  <ul id="j_defectList" class="optionsList">
    <?php foreach ($this->defects as $defect): ?>
      <li id="j_defectItem_<?php echo $defect->getId() ?>_">
        <div class="clearfixDashboard history">
          <div class="testlist-l" title="<?php echo $this->escapeQuotes($defect->getExtraData('name')) ?>">
            <p class="j_defectLink" key="<?php echo $defect->getExtraData('key') ?>">
              <a target="_blank" class="list_item_link" href="<?php echo $this->defectUrl($defect->getNo(), $this->bugTracker) ?>"><?php echo $defect->getExtraData('name') ?></a>
            </p>
            <p class="j_defectText" key="<?php echo $defect->getExtraData('key') ?>"><?php echo $defect->getExtraData('name') ?></p>
          </div>
          <div class="testlist-r">
            <span>
              <?php echo $this->defectStatusTag($defect, $this->bugTracker) ?>
            </span>

            <?php if (empty($defect->getTests())): ?>
              <?php if ($this->activeProject->isActive()
                        && $this->taskUserPermission->isDefectModifyPermission()
                        && $this->task->getStatusId() != Application_Model_TaskStatus::CLOSED):?>
                <a class="j_deleteDefectFromTask" data-defect-name="[<?php echo $this->escapeQuotes($defect->getNo()) ?>] <?php echo ($this->activeProject->getBugTracker()->getBugTrackerTypeId() == Application_Model_BugTrackerType::INTERNAL) ? $defect->getTitle() : $defect->getSummary() ?>" href="<?php echo $this->projectUrl(array('id' => $this->task->getId(), 'defectId' => $defect->getId()), 'task_delete_defect_ajax') ?>" title="<?php echo $this->t('Usuń') ?>"><span aria-hidden="true" class="icon_close icon-15"></span></a>
              <?php endif; ?>
            <?php endif; ?>
          </div>
        </div>
      </li>
      <?php if (!empty($defect->getTests())): ?>
        <?php foreach ($defect->getTests() as $test): ?>
          <li id="j_defectItem_<?php echo $defect->getId() ?>_<?php echo $test->getExtraData('task_test_id') ?>">
            <div class="clearfixDashboard history">
              <div style="padding-left: 30px;">
                <span class="list_item_arrow"></span>
                <a href="<?php echo $this->projectUrl(array('id' => $test->getExtraData('task_test_id')), $this->taskTestViewRouteName($test)) ?>">
                  <span class="object_nr"><?php echo $this->activeProject->getPrefix() .'-'. $test->getOrdinalNo() ?></span> <?php echo $test->getName() ?>
                </a>
              </div>
              <?php if ($this->activeProject->isActive()
                && $this->taskUserPermission->isDefectModifyPermission()
                && $this->task->getStatusId() != Application_Model_TaskStatus::CLOSED):?>
                <a class="j_deleteDefectFromTask" data-defect-name="[<?php echo $defect->getNo() ?>] <?php echo $this->escapeQuotes($defect->getSummary()) ?>" href="<?php echo $this->projectUrl(array('taskTestId' => $test->getExtraData('task_test_id'), 'defectId' => $defect->getId()), 'task_test_delete_defect_ajax') ?>" title="<?php echo $this->generalT('Usuń') ?>"><span aria-hidden="true" class="icon_close icon-15"></span></a>
              <?php endif; ?>
            </div>
          </li>
        <?php endforeach; ?>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>
</div>
<script type="text/javascript">
/* <![CDATA[ */
  url.defectStatusAjax = '<?php echo $this->projectUrl(array(), 'defect_status_ajax') ?>';
  language.defectNotExists = '<?php echo $this->generalT('Zgłoszenie nie istnieje.') ?>';
/* ]]> */
</script>