<script id="j_taskDefectItemsTmpl" type="text/x-jquery-tmpl">
<div id="j_defectContent">
  <ul id="j_defectList" class="optionsList">
  </ul>
</div>
</script>

<script id="j_taskDefectItemTmpl" type="text/x-jquery-tmpl">
<li id="j_defectItem_${itemId}">
  <div class="clearfixDashboard history">
    <div class="testlist-l" title="${name}">
      <p class="j_defectLink">
        <a <?php if ($this->activeProject->getBugTracker()->getBugTrackerTypeId() !== Application_Model_BugTrackerType::INTERNAL) { echo 'target="_blank"'; } ?> class="list_item_link" href="${viewUrl}"><span class="object_nr">${objectNumber}</span> ${name}</a>
      </p>
    </div>
    <div class="testlist-r">
      <span>
        <strong class="j_defectStatus">${status}</strong>
      </span>
      <?php if ($this->activeProject->isActive()
    && $this->taskUserPermission->isDefectModifyPermission()
    && $this->task->getStatusId() != Application_Model_TaskStatus::CLOSED):?>
        <a data-defect-name='[${objectNumber}] ${name}' class="j_deleteDefectFromTask" href="${deleteUrl}" title="<?php echo $this->partialT('Usuń', 'task-defect-tmpl', 'project') ?>"><span aria-hidden="true" class="icon_close icon-15"></span></a>
      <?php endif; ?>
    </div>
  </div>
</li>
</script>