<script id="j_taskTestItemsTmpl" type="text/x-jquery-tmpl">
<div id="j_testContent">
  <ul id="j_testList">
  </ul>
</div>
</script>

<script id="j_taskTestItemTmpl" type="text/x-jquery-tmpl">
<li id="j_testItem_${taskTestId}">
  <div class="clearfixDashboard history">
    <div class="testlist-l" title="${name}">
      <a href="${viewUrl}"><span class="object_nr">${objectNumber}</span> ${name}</a>
    </div>
    <div class="testlist-r">
      <span>
      </span>
      <?php if ($this->activeProject->isActive() 
                && $this->taskUserPermission->isTestModifyPermission()
                && $this->task->getStatusId() != Application_Model_TaskStatus::CLOSED):?>
        <a class="j_deleteTestFromTask" href="${deleteUrl}" title="<?php echo $this->t('Usuń') ?>"><span aria-hidden="true" class="icon_close icon-15"></span></a>
      <?php endif; ?>
    </div>
  </div>
</li>
</script>