<?php if (count($this->defects)): ?>
<div id="j_defectContent">
  <ul id="j_defectList">
    <?php foreach ($this->defects as $defect): ?>
      <li id="j_defectItem_<?php echo $defect->getId() ?>">
        <div class="clearfixDashboard history">
          <div class="testlist-l" title="<?php echo $defect->getExtraData('name') ?>">
            <a class="j_new_window" href="<?php echo $this->defectUrl($defect->getId(), $this->bugTracker) ?>"><span class="object_nr"><?php echo $defect->getObjectNumber() ?></span> <?php echo $defect->getTitle() ?></a>
          </div>
          <div class="testlist-r">
            <span>
              <?php echo $this->showDefectStatusIcon($defect) ?>
            </span>
            <?php if ($this->activeProject->isActive() 
                      && $this->taskUserPermission->isDefectModifyPermission()
                      && $this->task->getStatusId() != Application_Model_TaskStatus::CLOSED):?>
              <a class="j_deleteDefectFromTask" href="<?php echo $this->projectUrl(array('id' => $this->task->getId(), 'defectId' => $defect->getId()), 'task_delete_defect_ajax') ?>" title="<?php echo $this->t('Usuń') ?>"><span aria-hidden="true" class="icon_close icon-15"></span></a>
            <?php endif; ?>
          </div>                   
        </div>
      </li>              
    <?php endforeach; ?>
  </ul>
</div>
<?php endif;