<section id="content">
 <!-- <div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>  
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>  -->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array('id' => $this->project->getId()), 'admin_project_view')?>" ><?php echo $this->t('Właściwości projektu') ?></a></li>
      </ul>
    </nav>
    
    <div class="textLabelEditor">
      <div id="text" class="content_label_title"><?php echo $this->escapeQuotes($this->project->getName()) ?></div>
    </div>

    <?php if (count($this->resolutions) > 0): ?>

      <table>
        <thead>
          <tr>
            <th><?php echo $this->t('Nazwa') ?></th>
            <th><?php echo $this->t('Opis') ?></th>
            <th><?php echo $this->t('Liczba zadań') ?></th>
            <th><?php echo $this->t('Liczba testów') ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->resolutions as $resolution): ?>
          <tr>
            <td>
              <a href="<?php echo $this->url(array('id' => $resolution->getId()), 'admin_resolution_view') ?>">
                <?php echo $this->showResolutionIcon($resolution) ?> <?php echo $this->escapeQuotes($resolution->getName()) ?>
              </a>
            </td>
            <td><?php echo $this->escapeQuotes(nl2br($resolution->getDescription())) ?></td>
            <td class="t_number"><?php echo $resolution->getExtraData('taskCount') ?></td>
            <td class="t_number"><?php echo $resolution->getExtraData('testCount') ?></td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

    <?php else: ?>
      <div class="empty-text"><?php echo $this->t('Brak statusów.') ?></div>
    <?php endif; ?>

    <?php echo $this->partial('popups/delete-resolution.phtml') ?>
  </article>    
</section>