<section id="content">
 <!-- <div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>  
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>  -->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array('projectId' => $this->project->getId()), 'admin_resolution_add')?>" ><?php echo $this->t('Dodaj status') ?></a></li>
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array('id' => $this->project->getId()), 'admin_project_view')?>" ><?php echo $this->t('Właściwości projektu') ?></a></li>
      </ul>
    </nav>
    
    <div class="textLabelEditor">
      <div id="text" class="content_label_title"><?php echo $this->escapeQuotes($this->project->getName()) ?></div>
    </div>

    <?php if (count($this->resolutions) > 0): ?>

      <table>
        <thead>
          <tr>
            <th><?php echo $this->t('Nazwa') ?></th>
            <th><?php echo $this->t('Opis') ?></th>
            <th><?php echo $this->t('Liczba zadań') ?></th>
            <th><?php echo $this->t('Liczba testów') ?></th>
            <th class="action_list_th"><?php echo $this->t('Akcje') ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->resolutions as $resolution): ?>
          <tr>
            <td>
              <a href="<?php echo $this->url(array('id' => $resolution->getId()), 'admin_resolution_view') ?>">
                <?php echo $this->showResolutionIcon($resolution) ?> <?php echo $this->escapeQuotes($resolution->getName()) ?>
              </a>
            </td>
            <td><?php echo $this->escapeQuotes(nl2br($resolution->getDescription())) ?></td>
            <td class="t_number"><?php echo $resolution->getExtraData('taskCount') ?></td>
            <td class="t_number"><?php echo $resolution->getExtraData('testCount') ?></td>
            <td>
              <nav>
                <ul class="action_list">
                  <div class="popbox">
                    <a href="#" id="action_icon" class="open icon_cog icon-20"></a>
                    <div class='collapse'>
                      <ul class="box">           
                        <li><a href="<?php echo $this->url(array('id' => $resolution->getId()), 'admin_resolution_edit') ?>"><?php echo $this->t('Edytuj') ?></a></li>
                        <?php if ($resolution->getExtraData('taskCount') == 0 && $resolution->getExtraData('testCount') == 0): ?>
                          <li><a class="j_delete_resolution" href="<?php echo $this->url(array('id' => $resolution->getId()), 'admin_resolution_delete') ?>"><?php echo $this->t('Usuń') ?></a></li>
                        <?php endif; ?>
                      </ul> 
                    </div>
                  </div>                
                </ul>
              </nav>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

    <?php else: ?>
      <div class="empty-text"><?php echo $this->t('Brak statusów') ?></div>
    <?php endif; ?>

    <?php echo $this->partial('popups/delete-resolution.phtml') ?>
  </article>    
</section>