<section id="content">
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <?php if (count($this->environments) > 0): ?>

      <table>
        <thead>
          <tr>
            <th><?php echo $this->t('Środowisko') ?></th>
            <th><?php echo $this->t('Wszystkie zadania') ?></th>
            <th><?php echo $this->t('Zadania niewykonane') ?></th>
            <th><?php echo $this->t('Zadania zakończone') ?></th>
            <th><?php echo $this->t('Zadania zakończone powodzeniem') ?></th>
            <th><?php echo $this->t('Zadania zakończone niepowodzeniem') ?></th>
            <th><?php echo $this->t('Zadania w toku') ?></th>
            <th><?php echo $this->t('Zadania zawieszone') ?></th>
            <th style="width: 200px;"><?php echo $this->t('Postęp') ?> [%]</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->environments as $environment): ?>
          <tr>
            <td><?php echo $this->escapeQuotes($environment->getName()) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('allTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('openTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('closedTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('successTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('failedTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('inProgressTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($environment->getExtraData('suspendedTasks')) ?></td>
            <td>
              <?php echo $this->escapeQuotes($this->percent($environment->getExtraData('allTasks'), $environment->getExtraData('closedTasks'))) ?>
              <?php if ($environment->getExtraData('allTasks') > 0) { echo $this->partial('partials/tasks-percent-stripe.phtml', $environment->getAllExtraData()); } ?>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    
    <div class="button_edit"><a href="<?php echo $this->url(array(), 'report_export_all_task_run_statuses_for_environments') ?>"><?php echo $this->generalT('Eksportuj wszystko') ?></a></div>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-default.phtml'); ?>

    <?php else: ?>
    <div><?php echo $this->t('Brak wyników.') ?></div>
    <?php endif; ?>
    
  </article>    
</section>