<section id="content">
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <?php if (count($this->users) > 0): ?>

      <table>
        <thead>
          <tr>
            <th><?php echo $this->t('Użytkownik') ?></th>
            <th><?php echo $this->t('Wydanie') ?></th>
            <th><?php echo $this->t('Wszystkie zadania') ?></th>
            <th><?php echo $this->t('Zadania niewykonane') ?></th>
            <th><?php echo $this->t('Zadania zakończone') ?></th>
            <th><?php echo $this->t('Zadania zakończone powodzeniem') ?></th>
            <th><?php echo $this->t('Zadania zakończone niepowodzeniem') ?></th>
            <th><?php echo $this->t('Zadania w toku') ?></th>
            <th><?php echo $this->t('Zadania zawieszone') ?></th>
            <th style="width: 200px;"><?php echo $this->t('Postęp') ?> [%]</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->users as $user): ?>
          <tr>
            <!--<td><a href="<?php /*echo $this->url(array(
              'projectId'   => $this->activeProject->getId(),
              'assigneeId'  => $user->getId()
            ), 'report_user_task_run_list')*/ ?>"><?php //echo $this->escapeQuotes($user->getFullname()) ?></a></td>-->
            <td><?php echo $this->escapeQuotes($user->getFullname()) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('releaseName') === null ? $this->generalT('defaultReleaseName') : $user->getExtraData('releaseName')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('allTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('openTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('closedTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('successTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('failedTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('inProgressTasks')) ?></td>
            <td><?php echo $this->escapeQuotes($user->getExtraData('suspendedTasks')) ?></td>
            <td>
              <?php echo $this->escapeQuotes($this->percent($user->getExtraData('allTasks'), $user->getExtraData('closedTasks'))) ?>
              <?php if ($user->getExtraData('allTasks') > 0) { echo $this->partial('partials/tasks-percent-stripe.phtml', $user->getAllExtraData()); } ?>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    
    <div class="button_edit"><a href="<?php echo $this->url(array(), 'report_export_all_task_run_statuses_for_users') ?>"><?php echo $this->generalT('Eksportuj wszystko') ?></a></div>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-default.phtml'); ?>

    <?php else: ?>
    <div><?php echo $this->t('Brak wyników.') ?></div>
    <?php endif; ?>
    
  </article>    
</section>

<div>
  
</div>