<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Profil') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->   
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

      <div><?php echo $this->form->backUrl->renderViewHelper() ?></div>

        <div class="formContainer">
          <span>
        <?php echo $this->form->oldPassword->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('oldPassword', $this->t('Stare hasło')) ?>
        <?php foreach ($this->form->getErrors('oldPassword') as $error): ?>
        
        <div class="error_msg"><?php echo $this->errorT($error, array(
          'min' => $this->form->getElement('password')->getValidator('StringLength')->getMin(),
          'max' => $this->form->getElement('password')->getValidator('StringLength')->getMax(),
        )) ?></div>
        <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
        <?php echo $this->form->password->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('password', $this->t('Nowe hasło')) ?>
        <?php foreach ($this->form->getErrors('password') as $error): ?>
        
        <div class="error_msg"><?php echo $this->errorT($error, array(
          'min' => $this->form->getElement('password')->getValidator('StringLength')->getMin(),
          'max' => $this->form->getElement('password')->getValidator('StringLength')->getMax(),
        )) ?></div>
        <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
        <?php echo $this->form->confirmPassword->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('confirmPassword', $this->t('Powtórz hasło')) ?>
        <?php foreach ($this->form->getErrors('confirmPassword') as $error): ?>
        
        <div class="error_msg"><?php echo $this->errorT($error, array(
          'min' => $this->form->getElement('password')->getValidator('StringLength')->getMin(),
          'max' => $this->form->getElement('password')->getValidator('StringLength')->getMax(),
        )) ?></div>
        <?php endforeach; ?>
          </span>
        </div>

      <div>
        <span id="save"><?php echo $this->formSubmit('change', $this->t('Zmień hasło')) ?></span>
        <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
      </div>
      <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>

      <div>
        <?php echo $this->form->csrf->renderViewHelper() ?>
        <?php foreach ($this->form->getErrors('csrf') as $error): ?>
        <div><?php echo $this->errorT($error) ?></div>
        <?php endforeach; ?>
      </div>
    </form>
  </article>    
</section>