<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Projekty') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div> --> 
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" enctype="<?php echo $this->form->getEnctype() ?>">

      <div><?php echo $this->form->backUrl->renderViewHelper() ?></div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->file->renderFile() ?><span class="help item">?<div class="cloud"><?php echo $this->t('Dopuszczalne pliki') ?></div></span>
            <?php echo $this->formRequiredLabel('file', $this->t('Plik')) ?> 
              <?php foreach ($this->form->getErrors('file') as $error): ?>
                <span class="arrow_msg"></span>
                <div class="error_msg"><?php echo $this->errorT($error, array(
                  'maxFileSize' => $this->form->getElement('file')->getValidator('Size')->getMax(),
                  'extensions'  => implode(', ', $this->form->getElement('file')->getValidator('Extension')->getExtension())
                )) ?></div>
              <?php endforeach; ?>
              <?php if ($this->errorFile): ?>
                <div class="error_msg"><?php echo $this->errorT($this->errorFile) ?></div>
              <?php endif; ?>  
          </span>
        </div>

        <div class="formContainer">
          <span>
              <?php echo $this->form->name->renderViewHelper() ?>
              <?php echo $this->formRequiredLabel('name', $this->t('Nazwa')) ?>
              <?php foreach ($this->form->getErrors('name') as $error): ?>
                <div class="error_msg"><?php echo $this->errorT($error, array(
                  'min' => $this->form->getElement('name')->getValidator('StringLength')->getMin(),
                  'max' => $this->form->getElement('name')->getValidator('StringLength')->getMax()
                )) ?></div>
              <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
              <?php echo $this->form->prefix->renderViewHelper() ?><span class="help item">?<div class="cloud"><?php echo $this->t('Unikalny identyfikator') ?></div></span>
              <?php echo $this->formRequiredLabel('prefix', $this->t('Prefiks')) ?>
              <?php foreach ($this->form->getErrors('prefix') as $error): ?>
                <div class="error_msg"><?php echo $this->errorT($error, array(
                  'min' => $this->form->getElement('prefix')->getValidator('StringLength')->getMin(),
                  'max' => $this->form->getElement('prefix')->getValidator('StringLength')->getMax()
                )) ?></div>
              <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
              <?php echo $this->form->password->renderViewHelper() ?><span class="help item">?<div class="cloud"><?php echo $this->t('Hasło dotyczy') ?></div></span>
              <?php echo $this->formRequiredLabel('password', $this->t('Hasło dla użytkowników')) ?>
              <?php foreach ($this->form->getErrors('password') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('password')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('password')->getValidator('StringLength')->getMax()
              )) ?></div>
              <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
              <?php echo $this->form->confirmPassword->renderViewHelper() ?>
              <?php echo $this->formRequiredLabel('confirmPassword', $this->t('Powtórz hasło dla użytkowników')) ?>
              <?php foreach ($this->form->getErrors('confirmPassword') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('password')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('password')->getValidator('StringLength')->getMax()
              )) ?></div>
              <?php endforeach; ?>
          </span>
        </div>

            <div>
              <span id="save"><?php echo $this->formSubmit('import', $this->t('Importuj')) ?></span>
              <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
            </div>
            <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>

            <div>
              <?php echo $this->form->csrf->renderViewHelper() ?>
              <?php foreach ($this->form->getErrors('csrf') as $error): ?>
              <div><?php echo $this->errorT($error) ?></div>
              <?php endforeach; ?>
            </div>  

    </form>
    
  </article>    
</section>