<?php $this->filterRequestConditions($this->filterForm->getValues()) ?>

<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>   
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array(), 'admin_project_add')?>" ><?php echo $this->t('Dodaj projekt') ?></a></li>
        <li class="button_link_li"><a class="button_link" href="<?php echo $this->url(array(), 'admin_project_import')?>" ><?php echo $this->t('Importuj') ?></a></li>
      </ul>
    </nav>

    <form class="filterBox" name="<?php echo $this->filterForm->getName() ?>" method="<?php echo $this->filterForm->getMethod() ?>" action="<?php echo $this->filterForm->getAction() ?>">

      <div class="search_text">
        <div class="filter">
          <div><?php echo $this->formLabel('search', $this->t('Szukaj')) ?></div>
          <div class="search_in_filter"><?php echo $this->filterForm->search->renderViewHelper() ?><a href="#" id="j_searchButton" class="icon_search icon-20"></a></div>
        </div>
      </div>
      <div class="search_filter">
        <div class="filter">
          <div><?php echo $this->formLabel('status', $this->t('Status')) ?></div>
          <div class="custom-select-xsmall"><?php echo $this->filterForm->status->renderViewHelper() ?></div>
        </div>

        <div class="filter">
          <div><?php echo $this->formLabel('resultCountPerPage', $this->t('Wyniki')) ?></div>
          <div class="custom-select-xsmall"><?php echo $this->filterForm->resultCountPerPage->renderViewHelper() ?></div>
        </div>

        <div class="filterButton"><?php echo $this->formButton('j_filterButton', $this->t('Filtruj')) ?></div>
      </div>
    </form>

    <?php if (count($this->projects) > 0): ?>

      <table>
        <thead>
          <tr>
            <th><?php echo $this->sortingControl('Nazwa', 'project_name', 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->sortingControl('Prefiks', 'project_prefix', 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->t('Status') ?></th>
            <th><?php echo $this->sortingControl('Data utworzenia', 'project_create_date', 'sorting.phtml', $this->request) ?></th>
            <th class="action_list_th"><?php echo $this->t('Akcje') ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->projects as $project): ?>
          <tr>
            <td><a href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_view') ?>"><?php echo $this->escapeQuotes($project->getName()) ?></a></td>
            <td class="t_number"><?php echo $project->getPrefix() ?></td>
            <td class="t_status"><?php echo $this->statusT($project->getStatus(), 'PROJECT') ?></td>
            <td class="t_date"><?php echo $project->getCreateDate() ?></td>
            <td>
              <nav>
                <ul class="action_list">
                  <div class="popbox">
                    <a href="#" id="action_icon" class="open icon_cog icon-20"></a>
                    <div class='collapse'>
                      <ul class="box">           
                        <?php if ($project->getStatusId() != Application_Model_ProjectStatus::FINISHED): ?>            
                          <li><a href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_edit') ?>"><?php echo $this->t('Edytuj') ?></a></li>
                          <?php if ($project->getStatusId() == Application_Model_ProjectStatus::ACTIVE): ?>
                            <li><a href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_suspend') ?>"><?php echo $this->t('Zawieś') ?></a></li>
                          <?php elseif ($project->getStatusId() == Application_Model_ProjectStatus::SUSPENDED): ?>
                            <li><a href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_activate') ?>"><?php echo $this->t('Aktywuj') ?></a></li>
                          <?php endif; ?>
                          <li><a class="j_finish_project" href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_finish') ?>"><?php echo $this->t('Zakończ') ?></a></li>
                        <?php endif; ?>
                        <li><a href="<?php echo $this->url(array('projectId' => $project->getId()), 'admin_bug_tracker_list') ?>"><?php echo $this->t('Narzędzia śledzenia defektów') ?></a></li>
                        <li><a href="<?php echo $this->url(array('projectId' => $project->getId()), 'admin_resolution_list') ?>"><?php echo $this->t('Statusy rozwiązań') ?></a></li>
                        <li><a href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_export') ?>"><?php echo $this->t('Eksportuj') ?></a></li>
                        <!--<li><a href="<?php echo $this->url(array('id' => $project->getId()), 'admin_project_export_defects') ?>"><?php echo $this->t('Eksportuj defekty') ?></a></li>-->
                      </ul> 
                    </div>
                  </div>                
                </ul>
              </nav>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-filter.phtml', $this->request->getParams()); ?>

    <?php else: ?>
      <div class="empty-text"><?php echo $this->t('Brak projektów') ?></div>
    <?php endif; ?>
  </article>    
</section>

<?php echo $this->partial('popups/finish-project.phtml');