<?php echo $this->partial('header.phtml', array(
  'keywords'    => $this->keywords,
  'description' => $this->description,
  'messageBox'  => $this->messageBox,
  'language'    => $this->language,
  'locale'      => $this->locale,
  'cModule'     => $this->cModule,
  'cController'=> $this->cController,
  'cAction'     => $this->cAction
)); ?>
   
<header id="head-top" class="head-top-main">
  <div class="top_left">
    <?php echo $this->partial('/partials/projects-form.phtml', array(
      'projectsForm' => $this->projectsForm
    )); ?>
    <?php if ($this->activeProject !== null): ?>
      <?php if ($this->activeProject->isFinished()): ?>
        <span class="finishedProject"><span class="status_SUCCESS"></span><?php echo $this->generalT('Projekt zakończony') ?></span>
      <?php elseif ($this->activeProject->isSuspended()): ?>
        <span class="suspendedProject"><span class="status_SUSPENDED"></span><?php echo $this->generalT('Projekt zawieszony') ?></span>
      <?php endif; ?>
    <?php endif; ?>
  </div>
  
  <div class="top_right">   
    <a class="top_messages" href="<?php echo $this->url(array(), 'message_list', true)?>" title="<?php echo $this->generalT('Wiadomości') ?>"<?php if ($this->activeMenu == 'messages'): ?> class="activeMenu"<?php endif; ?>><span aria-hidden="true" class="icon_mail icon-20" style="line-height: 2.8;"></span></a> 
    <a href="<?php echo $this->url(array(), 'user_profile') ?>" class="top_avatar_header">
      <span class="user-info"><?php echo $this->authUser->getFullname()?> <br><small><?php echo $this->authUser->getEmail()?></small></span>
      <span class="user-thumb"><p class="avatar_header"><img src="<?php echo $this->authUser->getAvatarUrl(true) ?>" alt="<?php echo $this->authUser->getFullname()?>" /></p></span>
    </a>
    
    <?php if ($this->authUser->getAdministrator()): ?>
      <div class="header_admin"><a href="<?php echo $this->url(array(), 'admin_index')?>" title="<?php echo $this->generalT('Administracja') ?>"><span aria-hidden="true" class="icon_tools icon-20" style="line-height: 2.8;"></span></a></div>
    <?php endif; ?>
      
    <div class="header_logout"><a href="<?php echo $this->url(array(), 'user_logout')?>" title="<?php echo $this->generalT('Wyloguj') ?>"><span class="icons-switch icon-20" style="line-height: 2.8;"></span></a></div>
  </div>  
</header>

<aside id="left_header_menu">
  <a id="header_logo" href="<?php echo $this->url(array(), 'index')?>" ></a>
  <div id="wrapper">
    <ul class="menu">
      <li class="item1"><a href="<?php echo $this->url(array(), 'index')?>"<?php if ($this->activeMenu == 'dashboard'): ?> class="activeMenu"<?php endif; ?>><span aria-hidden="true" class="icon_grid-2x2 icon-20"></span><?php echo $this->generalT('Kokpit') ?></a></li>
    </ul>
  </div>
</aside>
<div id="right_sidebar">
  <?php echo $this->layout()->content ?>
</div>

<?php echo $this->partial('footer.phtml', array('locale' => $this->locale));