<section id="content">
  <article class="article_in_content dashboard">

    <?php if ($this->filterForm !== null): ?>   
    <?php $this->filterRequestConditions($this->filterForm->getValues()) ?>
    <article class="column_dashboard">
      <form name="<?php echo $this->filterForm->getName() ?>" method="<?php echo $this->filterForm->getMethod() ?>" action="<?php echo $this->filterForm->getAction() ?>">
        
        <?php echo $this->filterForm->onlyActiveRelease->renderViewHelper() ?>
        <?php echo $this->formLabel('onlyActiveRelease', $this->t('Pokaż tylko dla aktywnego wydania NAME', array('name' => $this->activeRelease->getName()))) ?>
        
      </form>
    </article>
    <?php endif;?>
        
    <?php        
    if ($this->activeProject === null)
    {
      echo $this->partial('partials/task-statistics.phtml', array(
        'authUser' => $this->authUser,
        'mainLinkPart' => $this->mainLinkPart,
        'numberOfTasksAssignedToMe' => $this->numberOfTasksAssignedToMe,
        'percentOfTasksAssignedToMe' => $this->percentOfTasksAssignedToMe,
        'numberOfOpenTasksAssignedToMe' => $this->numberOfOpenTasksAssignedToMe,
        'percentOfOpenTasksAssignedToMe' => $this->percentOfOpenTasksAssignedToMe,
        'numberOfReopenTasksAssignedToMe' => $this->numberOfReopenTasksAssignedToMe,
        'percentOfReopenTasksAssignedToMe' => $this->percentOfReopenTasksAssignedToMe,
        'numberOfInProgressTasksAssignedToMe' => $this->numberOfInProgressTasksAssignedToMe,
        'percentOfInProgressTasksAssignedToMe' => $this->percentOfInProgressTasksAssignedToMe,
        'numberOfClosedTasksAssignedToMe' => $this->numberOfClosedTasksAssignedToMe,
        'percentOfClosedTasksAssignedToMe' => $this->percentOfClosedTasksAssignedToMe,
        'json_numberOfTasksAssignedToMeGroupedByStatus' => $this->json_numberOfTasksAssignedToMeGroupedByStatus
      ));
    }
    else
    {
      echo $this->partial('partials/task-statistics-active-project.phtml', array(
        'authUser' => $this->authUser,
        'activeProject' => $this->activeProject,
        'mainLinkPart' => $this->mainLinkPart,
        'numberOfTasksAssignedToMe' => $this->numberOfTasksAssignedToMe,
        'percentOfTasksAssignedToMe' => $this->percentOfTasksAssignedToMe,
        'numberOfOpenTasksAssignedToMe' => $this->numberOfOpenTasksAssignedToMe,
        'percentOfOpenTasksAssignedToMe' => $this->percentOfOpenTasksAssignedToMe,
        'numberOfReopenTasksAssignedToMe' => $this->numberOfReopenTasksAssignedToMe,
        'percentOfReopenTasksAssignedToMe' => $this->percentOfReopenTasksAssignedToMe,
        'numberOfInProgressTasksAssignedToMe' => $this->numberOfInProgressTasksAssignedToMe,
        'percentOfInProgressTasksAssignedToMe' => $this->percentOfInProgressTasksAssignedToMe,
        'numberOfClosedTasksAssignedToMe' => $this->numberOfClosedTasksAssignedToMe,
        'percentOfClosedTasksAssignedToMe' => $this->percentOfClosedTasksAssignedToMe,
        'json_numberOfTasksAssignedToMeGroupedByStatus' => $this->json_numberOfTasksAssignedToMeGroupedByStatus
      ));
    }
    ?>
    <article class="article_left">
      <?php echo $this->partial('partials/my-tasks.phtml', array(
        'activeProject' => $this->activeProject,
        'mainLinkPart' => $this->mainLinkPart,
        'lastNotClosedTasksAssignedToMe' => $this->lastNotClosedTasksAssignedToMe,
        'numberOfNotClosedTasksAssignedToMe' => $this->numberOfNotClosedTasksAssignedToMe        
      )); ?>
    </article> 

    <article class="article_right">
      <?php echo $this->partial('partials/my-overdue-tasks.phtml', array(
        'activeProject' => $this->activeProject,
        'mainLinkPart' => $this->mainLinkPart,
        'overdueTasksAssignedToMe' => $this->overdueTasksAssignedToMe,
        'numberOfOverdueTasksAssignedToMe' => $this->numberOfOverdueTasksAssignedToMe
      )); ?>
      
      <?php echo $this->partial('partials/my-messages.phtml', array(
        'activeProject' => $this->activeProject,
        'latestMessages' => $this->latestMessages,
        'numberOfUnreadMessages' => $this->numberOfUnreadMessages,
        'purifier' => $this->purifier
      )); ?>
    </article> 
    
  </article>
</section>