<?php
return array(
  Application_Model_RoleAction::PROJECT_ATTACHMENT,
  Application_Model_RoleAction::PROJECT_STATUS,
  Application_Model_RoleAction::REPORT_GENERATE,
  Application_Model_RoleAction::RELEASE_MANAGEMENT,
  
  Application_Model_RoleAction::VERSION_MANAGEMENT,
  Application_Model_RoleAction::ENVIRONMENT_MANAGEMENT,
  Application_Model_RoleAction::TAG_MANAGEMENT,
  
  Application_Model_RoleAction::TASK_ADD,
  Application_Model_RoleAction::TASK_ASSIGN_ALL,
  Application_Model_RoleAction::TASK_EDIT_ALL,
  Application_Model_RoleAction::TASK_DELETE_ALL,
  Application_Model_RoleAction::TASK_CHANGE_STATUS_ALL,
  Application_Model_RoleAction::TASK_EDIT_CREATED_BY_YOU,
  Application_Model_RoleAction::TASK_DELETE_CREATED_BY_YOU,
  Application_Model_RoleAction::TASK_CHANGE_STATUS_CREATED_BY_YOU,
  Application_Model_RoleAction::TASK_CHANGE_STATUS_ASSIGNED_TO_YOU,
  Application_Model_RoleAction::TASK_EDIT_ASSIGNED_TO_YOU,
  Application_Model_RoleAction::TASK_DELETE_ASSIGNED_TO_YOU,
  
  Application_Model_RoleAction::DEFECT_ADD,
  Application_Model_RoleAction::DEFECT_ASSIGN_ALL,
  Application_Model_RoleAction::DEFECT_EDIT_ALL,
  Application_Model_RoleAction::DEFECT_DELETE_ALL,
  Application_Model_RoleAction::DEFECT_CHANGE_STATUS_ALL,
  Application_Model_RoleAction::DEFECT_EDIT_CREATED_BY_YOU,
  Application_Model_RoleAction::DEFECT_DELETE_CREATED_BY_YOU,
  Application_Model_RoleAction::DEFECT_CHANGE_STATUS_CREATED_BY_YOU,
  Application_Model_RoleAction::DEFECT_DELETE_ASSIGNED_TO_YOU,
  Application_Model_RoleAction::DEFECT_CHANGE_STATUS_ASSIGNED_TO_YOU,
  Application_Model_RoleAction::DEFECT_EDIT_ASSIGNED_TO_YOU,
  
  Application_Model_RoleAction::TEST_ADD,
  Application_Model_RoleAction::TEST_EDIT_ALL,
  Application_Model_RoleAction::TEST_EDIT_CREATED_BY_YOU,
  Application_Model_RoleAction::TEST_DELETE_ALL,
  Application_Model_RoleAction::TEST_DELETE_CREATED_BY_YOU,
  Application_Model_RoleAction::TASK_TEST_MODIFY_ALL,
  Application_Model_RoleAction::TASK_TEST_MODIFY_ASSIGNED_TO_YOU,
  Application_Model_RoleAction::TASK_TEST_MODIFY_CREATED_BY_YOU,
  Application_Model_RoleAction::TASK_DEFECT_MODIFY_ALL,
  Application_Model_RoleAction::TASK_DEFECT_MODIFY_ASSIGNED_TO_YOU,
  Application_Model_RoleAction::TASK_DEFECT_MODIFY_CREATED_BY_YOU
);