<section id="content">
  <article class="article_in_content">
  <?php if(APPLICATION_ENV == 'production') : ?>
    <p><?php echo  $this->t('Błąd aplikacji') ?><p>
  <?php else : ?>
    <h1><?php echo  $this->t('Błąd aplikacji') ?></h1>

    <?php if (isset($this->exception)): ?>

    <h3>Exception information:</h3>
    <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escapeQuotes(var_export($this->request->getParams(), true)) ?></pre>
    <?php endif; ?>

  <?php endif; ?>
  </article>    
</section>