<section id="content">
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <table>
      <thead>
        <tr>
          <th><?php echo $this->t('Wszystkie zadania') ?></th>
          <th><?php echo $this->t('Zadania niewykonane') ?></th>
          <th><?php echo $this->t('Zadania zakończone') ?></th>
          <th><?php echo $this->t('Zadania zakończone powodzeniem') ?></th>
          <th><?php echo $this->t('Zadania zakończone niepowodzeniem') ?></th>
          <th><?php echo $this->t('Zadania w toku') ?></th>
          <th><?php echo $this->t('Zadania zawieszone') ?></th>
          <th style="width: 200px;"><?php echo $this->t('Postęp') ?> [%]</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('allTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('openTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('closedTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('successTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('failedTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('inProgressTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($this->project->getExtraData('suspendedTasks')) ?></td>
          <td>
            <?php echo $this->escapeQuotes($this->percent($this->project->getExtraData('allTasks'), $this->project->getExtraData('closedTasks'))) ?>
            <?php if ($this->project->getExtraData('allTasks') > 0) { echo $this->partial('partials/tasks-percent-stripe.phtml', $this->project->getAllExtraData()); } ?></td>
        </tr>
      </tbody>
    </table>
    
    <div class="button_edit"><a href="<?php echo $this->url(array(), 'report_export_task_run_statuses_for_project') ?>"><?php echo $this->generalT('Eksportuj wszystko') ?></a></div>
    
  </article>    
</section>