<section id="content">
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <table>
      <thead>
        <tr>
          <th><?php echo $this->t('Typ') ?></th>
          <th><?php echo $this->t('Wszystkie zadania') ?></th>
          <th><?php echo $this->t('Zadania niewykonane') ?></th>
          <th><?php echo $this->t('Zadania zakończone') ?></th>
          <th><?php echo $this->t('Zadania zakończone powodzeniem') ?></th>
          <th><?php echo $this->t('Zadania zakończone niepowodzeniem') ?></th>
          <th><?php echo $this->t('Zadania w toku') ?></th>
          <th><?php echo $this->t('Zadania zawieszone') ?></th>
          <th style="width: 200px;"><?php echo $this->t('Postęp') ?> [%]</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->tasks as $task): ?>
        <tr>
          <td><?php echo $this->typeT($task->getType(), 'TASK') ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('allTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('openTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('closedTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('successTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('failedTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('inProgressTasks')) ?></td>
          <td><?php echo $this->escapeQuotes($task->getExtraData('suspendedTasks')) ?></td>
          <td>
            <?php echo $this->escapeQuotes($this->percent($task->getExtraData('allTasks'), $task->getExtraData('closedTasks'))) ?>
            <?php if ($task->getExtraData('allTasks') > 0) { echo $this->partial('partials/tasks-percent-stripe.phtml', $task->getAllExtraData()); } ?>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    
    <div class="button_edit"><a href="<?php echo $this->url(array(), 'report_export_all_task_run_statuses_by_type') ?>"><?php echo $this->generalT('Eksportuj wszystko') ?></a></div>
    
  </article>    
</section>