<section id="content">
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <ul>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_for_project') ?>"><?php echo $this->t('Statusy zadań dla projektu') ?></a></li>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_for_releases') ?>"><?php echo $this->t('Statusy zadań dla wydań') ?></a></li>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_for_phases') ?>"><?php echo $this->t('Statusy zadań dla faz w wydaniach') ?></a></li>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_for_environments') ?>"><?php echo $this->t('Statusy zadań dla środowisk') ?></a></li>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_by_type') ?>"><?php echo $this->t('Statusy zadań według typu') ?></a></li>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_by_priority') ?>"><?php echo $this->t('Statusy zadań według priorytetu') ?></a></li>
      <li><a href="<?php echo $this->url(array(), 'report_task_run_statuses_for_users') ?>"><?php echo $this->t('Statusy zadań dla użytkowników w wydaniach') ?></a></li>
    </ul>
    
  </article>    
</section>