<section id="content">
 <!-- <div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#">Narzędzia</a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>  -->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

      <div><?php echo $this->form->backUrl->renderViewHelper() ?></div>

          <div>
            <?php echo $this->form->project->renderViewHelper() ?>
            <?php foreach ($this->form->getErrors('project') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </div>
          
          
        <div class="formContainer full">
          <span>
            <?php echo $this->form->name->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('name', $this->t('Nazwa')) ?>
            <?php foreach ($this->form->getErrors('name') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('name')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('name')->getValidator('StringLength')->getMax()
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->url->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('url', $this->t('Adres URL')) ?>
            <?php foreach ($this->form->getErrors('url') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->projectName->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('projectName', $this->t('Nazwa projektu Mantis')) ?>
            <?php foreach ($this->form->getErrors('projectName') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('projectName')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('projectName')->getValidator('StringLength')->getMax()
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <?php echo $this->form->userName->renderViewHelper() ?>
            <?php echo $this->formLabel('userName', $this->t('Nazwa użytkownika')) ?>
            <?php foreach ($this->form->getErrors('userName') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('userName')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('userName')->getValidator('StringLength')->getMax()
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <input type="password" name="password" id="password" value="<?php echo $this->form->getValue('password') ?>">
            <?php echo $this->formLabel('password', $this->t('Hasło')) ?>
            <?php foreach ($this->form->getErrors('password') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <?php echo $this->form->activate->renderViewHelper() ?><?php echo $this->formLabel('activate', $this->t('Aktywuj po edycji')) ?>
            <?php foreach ($this->form->getErrors('activate') as $error): ?>
              <div><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

          <div style="margin-top:15px">
            <span id="save"><?php echo $this->formSubmit('save', $this->t('Zapisz')) ?></span>
            <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
          </div>
          <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>

          <div>
            <?php echo $this->form->csrf->renderViewHelper() ?>
            <?php foreach ($this->form->getErrors('csrf') as $error): ?>
            <div><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </div>      
 
    </form>
  </article>    
</section>