<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Baza testów') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
      <div><?php echo $this->form->backUrl->renderViewHelper() ?></div>

        <div class="formContainer full">
          <span>
            <?php echo $this->form->name->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('name', $this->t('Nazwa')) ?>
            <?php foreach ($this->form->getErrors('name') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'min' => $this->form->getElement('name')->getValidator('StringLength')->getMin(),
                'max' => $this->form->getElement('name')->getValidator('StringLength')->getMax()
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer full">
          <span>
            <?php echo $this->form->description->renderViewHelper() ?>
            <?php echo $this->formLabel('description', $this->t('Opis')) ?>
            <?php foreach ($this->form->getErrors('description') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
        
        <div class="formContainer full">
          <div>
            <?php echo $this->formRequiredLabel('items', $this->t('Pozycje')) ?>
            <div id="j_checklistItems">
              <?php foreach ($this->form->getItemIndexes() as $index): ?>
              <div id="j_checklistItem_<?php echo $index; ?>" class="j_checklistItem">
                <?php echo $this->form->getElement('itemId_'.$index)->renderViewHelper() ?>
                <?php echo $this->form->getElement('itemName_'.$index)->renderViewHelper() ?>
                <a href="#" id="j_removeChecklistItemButton_<?php echo $index; ?>" class="j_removeChecklistItemButton"><span class="icon_close icon-17" aria-hidden="true"></a>
                <?php foreach ($this->form->getErrors('itemName_'.$index) as $error): ?>
                  <div class="error_msg"><?php echo $this->errorT($error, array(
                    'min' => $this->form->getElement('name')->getValidator('StringLength')->getMin(),
                    'max' => $this->form->getElement('name')->getValidator('StringLength')->getMax()
                  )) ?></div>
                <?php endforeach; ?>
              </div>
              <?php endforeach; ?>
            </div>
            <div><a id="j_addChecklistItemButton" href="#"><?php echo $this->t('Dodaj pozycję') ?></a></div>
            <?php foreach ($this->form->getErrors('itemNames') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </div>
        </div>
        
        <?php echo $this->partial('partials/attachments-form.phtml', array('form' => $this->form)); ?>

        <div>
          <span id="save"><?php echo $this->formSubmit('add', $this->t('Zapisz')) ?></span>
          <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
        </div>
        <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div> 

        <div>
          <?php echo $this->form->csrf->renderViewHelper() ?>
          <?php foreach ($this->form->getErrors('csrf') as $error): ?>
          <div><?php echo $this->errorT($error) ?></div>
          <?php endforeach; ?>
        </div>

     
    </form>
  </article>
</section>
<?php echo $this->partial('partials/checklist.phtml'); ?>

<script type="text/javascript">
/* <![CDATA[ */
  language.charactersLeft = '<?php echo $this->generalT('Pozostało __left__/__max__ znaków.') ?>';
/* ]]> */
</script>