<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#">Przypadek testowy</a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->  
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
      <div><?php echo $this->form->backUrl->renderViewHelper() ?></div>
      <div><?php echo $this->form->taskIds->renderViewHelper() ?></div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->releaseName->renderViewHelper() ?>
            <div><?php echo $this->form->releaseId->renderViewHelper() ?></div>
            <?php echo $this->formRequiredLabel('releaseName', $this->t('Wydanie')) ?>
            <?php foreach ($this->form->getErrors('releaseId') as $error): ?>            
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->environments->renderViewHelper() ?>
            <?php echo $this->formLabel('environments', $this->t('Środowiska')) ?>  
            <?php foreach ($this->form->getErrors('environments') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->versions->renderViewHelper() ?>
            <?php echo $this->formLabel('versions', $this->t('Wersje')) ?>  
            <?php foreach ($this->form->getErrors('versions') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <?php echo $this->form->priority->renderViewHelper() ?>
            <?php echo $this->formRequiredLabel('priority', $this->t('Priorytet')); ?>  
            <?php foreach ($this->form->getErrors('priority') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div class="formContainer">
          <span>
            <?php echo $this->form->dueDate->renderViewHelper() ?><span class="calendar_icon"></span>
            <?php echo $this->formRequiredLabel('dueDate', $this->t('Termin realizacji')) ?>
            <?php foreach ($this->form->getErrors('dueDate') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error, array(
                'date'    => $this->form->getMinDate(),
                'min'     => $this->form->getMinDate(),
                'max'     => $this->form->getMaxDate(),
                'format'  => 'RRRR-MM-DD GG:MM'
              )) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer">
          <span>
            <div><?php echo $this->form->assigneeName->renderViewHelper() ?></div>
            <div><?php echo $this->form->assigneeId->renderViewHelper() ?></div>
            <?php echo $this->formRequiredLabel('assigneeName', $this->t('Przypisz do')) ?><span><a id="j_assignToMe" href="#"><?php echo $this->t('Przypisz do mnie') ?></a></span>
            <?php foreach ($this->form->getErrors('assigneeId') as $error): ?>
              <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>
          
        <div class="formContainer full">
          <span>
            <?php echo $this->form->comment->renderViewHelper() ?>
            <?php echo $this->formLabel('comment', $this->t('Komentarz')) ?>  
            <?php foreach ($this->form->getErrors('comment') as $error): ?>
                <div class="error_msg"><?php echo $this->errorT($error) ?></div>
            <?php endforeach; ?>
          </span>
        </div>

        <div>
          <span id="save"><?php echo $this->formSubmit('forward', $this->t('Przekaż')) ?></span>
          <span class="j_cancel_button"><a href="#"><?php echo $this->generalT('Anuluj') ?></a></span>
        </div>
        <div class="required_text"><?php echo $this->generalT('Pole wymagane') ?></div>

        <div>
          <?php echo $this->form->csrf->renderViewHelper() ?>
          <?php foreach ($this->form->getErrors('csrf') as $error): ?>
          <div><?php echo $this->errorT($error) ?></div>
          <?php endforeach; ?>
        </div>
     
    </form>
  </article>
</section>

<?php if (isset($this->prePopulatedEnvironments)) :?>
  <script type="text/javascript">
  /* <![CDATA[ */
    prePopulated['environments'] = <?php echo $this->prePopulatedEnvironments?>;
  /* ]]> */
  </script>
<?php endif?>

<?php if (isset($this->prePopulatedVersions)) :?>
  <script type="text/javascript">
  /* <![CDATA[ */
    prePopulated['versions'] = <?php echo $this->prePopulatedVersions?>;
  /* ]]> */
  </script>
<?php endif?>

<?php if ($this->form->getMaxDate() !== null) :?>
  <script type="text/javascript">
  /* <![CDATA[ */
    var maxDate = '<?php echo $this->form->getMaxDate() ?>';
  /* ]]> */
  </script>
<?php endif?>

<script type="text/javascript">
/* <![CDATA[ */
  language.charactersLeft = '<?php echo $this->generalT('Pozostało __left__/__max__ znaków.') ?>';
  language.defaultReleaseName = '<?php echo $this->generalT('defaultReleaseName') ?>';

  var autocompleteData = {
    url: '<?php echo $this->projectUrl(array(), 'project_user_list_ajax') ?>',
    textInputName: '#assigneeName',
    dstName: '#assigneeId'
  };
  
  var minDate = '<?php echo $this->form->getMinDate() ?>';
  var currentUser = {id: <?php echo $this->authUser->getId() ?>, name: '<?php echo $this->authUser->getFullname().' ('.$this->authUser->getEmail().')' ?>'};
  url.environmentListAjax = '<?php echo $this->projectUrl(array(), 'environment_list_ajax') ?>';
  url.versionListAjax = '<?php echo $this->projectUrl(array(), 'version_list_ajax') ?>';

  var defaultReleaseId = <?php echo $this->form->getDefaultReleaseId() ?>;
  
  var autocompleteRelease = {
    url: '<?php echo $this->projectUrl(array(), 'release_list_for_forward_ajax') ?>',
    textInputName: '#releaseName',
    dstName: '#releaseId'
  };
/* ]]> */
</script>