<?php $this->filterRequestConditions($this->filterForm->getValues()) ?>

<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#">Przypadek testowy</a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>
    
    <form class="filterBox" name="<?php echo $this->filterForm->getName() ?>" method="<?php echo $this->filterForm->getMethod() ?>" action="<?php echo $this->filterForm->getAction() ?>">

      <div class="filter">
        <div><?php echo $this->formLabel('search', $this->generalT('Szukaj')) ?></div>
        <div><?php echo $this->filterForm->search->renderViewHelper() ?></div>
      </div>
      
      <div class="filter">
        <div><?php echo $this->formLabel('type', $this->t('Typ')) ?></div>
        <div class="custom-select-xsmall"><?php echo $this->filterForm->type->renderViewHelper() ?></div>
      </div>
      
      <div class="filter">
        <div><?php echo $this->formLabel('author', $this->t('Autor')) ?></div>
        <div class="custom-select-xsmall"><?php echo $this->filterForm->author->renderViewHelper() ?></div>
      </div>

      <div class="filter">
        <div><?php echo $this->formLabel('resultCountPerPage', $this->generalT('Wyniki')) ?></div>
        <div class="custom-select-xsmall"><?php echo $this->filterForm->resultCountPerPage->renderViewHelper() ?></div>
      </div>

        <div class="filterButton"><?php echo $this->formButton('j_filterButton', $this->generalT('Filtruj')) ?></div>
        <div class="filterButton"><?php echo $this->formButton('j_filterAndSaveButton', $this->generalT('Filtruj i zapisz')) ?></div>
        <div class="filterButton"><?php echo $this->formButton('j_restoreButton', $this->generalT('Przywróć')) ?></div>
        <div class="filterButton"><?php echo $this->formButton('j_clearButton', $this->generalT('Wyczyść')) ?></div>
    </form>

    <?php if (count($this->tests) > 0): ?>
    <form name="<?php echo $this->checkboxListForm->getName() ?>" method="<?php echo $this->checkboxListForm->getMethod() ?>" action="<?php echo $this->checkboxListForm->getAction() ?>">
      <table>
        <thead>
          <tr>
            <th><?php echo $this->sortingControl('Nr obiektu', 'ordinal_no', 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->sortingControl('Nazwa', 'test_name', 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->sortingControl('Typ', 'test_type', 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->sortingControl('Autor', $this->createSortedFieldName('test', 'email', array('author')), 'sorting.phtml', $this->request) ?></th>
            <th><?php echo $this->sortingControl('Data utworzenia', 'test_create_date', 'sorting.phtml', $this->request) ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->tests as $test): ?>
          <tr>
            <td class="t_object_number"><?php echo $this->escapeQuotes($test->getObjectNumber()) ?></td>
            <td><a href="<?php echo $this->projectUrl(array('id' => $test->getId()), $this->testViewRouteName($test))?>"><?php echo $this->escapeQuotes($test->getName()) ?></a></td>
            <td class="t_status"><?php echo $this->typeT($test->getType(), 'TEST') ?></td>
            <td class="t_user"><?php echo $this->escapeQuotes($test->getAuthor()->getFullname()) ?></td>
            <td class="t_date"><?php echo $test->getCreateDate() ?></td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-filter.phtml', $this->request->getParams()); ?>

    </form>
    <?php else: ?>
      <div class="empty-text"><?php echo $this->t('Brak elementów bazy testów') ?></div>
    <?php endif;?>
  </article>    
</section>
<script type="text/javascript">
/* <![CDATA[ */
  var filterDefaultValues = <?php echo $this->filterForm->getDefaultValues(); ?>;
  var filterSavedValues = <?php echo $this->filterForm->getSavedValues(); ?>;
/* ]]> */
</script>