<section id="content">
 <!-- <div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Baza testów') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div>-->
  <article class="article_in_content">
    <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

    <nav class="button_link_nav">
      <ul class="button_link_ul">
        <?php if ($this->activeProject->isActive()): ?>
        
          <?php echo $this->prevTest($this->testCase->getPrevious()) ?>
          <?php foreach ($this->prepareTestActions($this->testCase, array(), $this->testUserPermission) as $action): ?>
            <?php if ($action === null): ?>
              <li class="button_link_li separator"></li>
            <?php else: ?>
              <li class="button_link_li"><a class="button_link <?php if (array_key_exists('class', $action)):?><?php echo $action['class'] ?><?php endif;?>" href="<?php echo $action['url'] ?>"><?php echo $this->t($action['text']) ?></a></li>
            <?php endif; ?>
          <?php endforeach; ?>
          <?php echo $this->nextTest($this->testCase->getNext()) ?>
          
        <?php endif; ?>
      </ul>
    </nav>

    <div class="textLabelEditor">
      <div id="text" class="content_label_title"><span class="object_nr"><?php echo $this->escapeQuotes($this->testCase->getObjectNumber()) ?></span> <?php echo $this->escapeQuotes($this->testCase->getName()) ?></div>
    </div>    
    
    <div class="contentLRtable">   
      
      <div class="contentProperties_left">
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Status') ?>: </div>
          <div id="text" class="content_label"><?php echo $this->statusT($this->testCase->getStatus(), 'TEST') ?></div>
        </div>
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Założenia wstępne') ?>: </div>
          <div id="text" class="content_label"> <?php echo nl2br($this->escapeQuotes($this->testCase->getPresuppositions())) ?></div>
        </div>
        <div class="textLabelPropertiesDiv" style="border-bottom:0px solid;">
          <div class="textLabelEditor_text"><?php echo $this->t('Rezultat oczekiwany') ?>: </div>
          <div id="text" class="content_label"> <?php echo nl2br($this->escapeQuotes($this->testCase->getResult())) ?></div>
        </div>
        
        <div>
            <h5 class="break_page"><span aria-hidden="true" class="icon_pencil icon-20"></span><?php echo $this->t('Opis') ?></h5>
            <div><?php echo nl2br($this->escapeQuotes($this->testCase->getDescription())) ?></div>
        </div>        
        
      </div>
      
      <div class="contentEditUser_right">
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Autor') ?>: </div>
          <div id="text" class="content_label"><?php echo $this->escapeQuotes($this->testCase->getAuthor()->getFullname()) ?></div>
        </div>        
        <div class="textLabelPropertiesDiv" style="border-bottom:0px solid;">
          <div class="textLabelEditor_text"><?php echo $this->t('Data utworzenia') ?>: </div>
          <div id="text" class="content_label"> <?php echo $this->testCase->getCreateDate() ?></div>
        </div>
      </div>
      
    </div>
    
    <?php if (count($this->testCase->getExtraData('attachments'))): ?>
    <div>
      <h4><?php echo $this->t('Załączniki') ?></h4>
      <?php foreach ($this->testCase->getExtraData('attachments') as $file): ?>
      <a href="<?php echo $this->url(array('id' => $file->getId()), 'file_download') ?>"><span class="fileElement"><span><?php echo $file->getFullName() ?></span></span></a>
      <?php endforeach; ?>
    </div>
    <?php endif; ?>
    
  </article>    
</section>

<?php echo $this->partial('popups/delete-test.phtml');
  
  