<section id="content">
  <!--<div class="breadcrumb">
    <a class="icon_house_alt" href="#"></a>
    <i class="arrow_carrot-right icon-15"></i>
    <a href="#"><?php echo $this->generalT('Baza testów') ?></a>
    <i class="arrow_carrot-right icon-15"></i>    
    <div class="active_bc"><?php echo $this->t('pageTitle') ?></div>
  </div> -->
  <article class="article_in_content">
    <div class="content_header">
      <h1 class="content_title"><?php echo $this->t('pageTitle') ?></h1>

      <nav class="button_link_nav">
        <ul class="button_link_ul">
          <li class="button_link_li"><a class="button_link" href="<?php echo $this->backUrl ?>"><?php echo $this->generalT('Powrót') ?></a></li>
          <?php if ($this->activeProject->isActive()): ?>

            <?php foreach ($this->prepareTestActions($this->checklist, array(), $this->testUserPermission) as $action): ?>
              <?php if ($action === null): ?>
                <li class="button_link_li separator"></li>
              <?php else: ?>
                <li class="button_link_li"><a <?php if (array_key_exists('type', $action) && $action['type'] == 'delete'): ?>data-name="test<?php echo $this->activeProject->getId(); ?>" data-item-id="<?php echo $this->checklist->getId() ?>"<?php endif; ?>class="button_link <?php if (array_key_exists('class', $action)):?><?php echo $action['class'] ?><?php endif;?>" href="<?php echo $action['url'] ?>"><?php echo $this->t($action['text']) ?></a></li>
              <?php endif; ?>
            <?php endforeach; ?>
          <?php endif; ?>
        </ul>
      </nav>
    </div>
    <div class="textLabelEditor">
      <div id="text" class="content_label_title"><span class="object_nr"><?php echo $this->escapeQuotes($this->checklist->getObjectNumber()) ?></span> <?php echo $this->spaceToEntity($this->escapeQuotes($this->checklist->getName())) ?></div>
    </div>

    <div class="contentLRtable">

      <div class="contentProperties_left">
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Status') ?>: </div>
          <div id="text" class="content_label"><?php echo $this->statusT($this->checklist->getStatus(), 'TEST') ?></div>
        </div>
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Opis') ?>: </div>
          <div id="text" class="content_label"> <?php echo nl2br($this->escapeQuotes($this->checklist->getDescription())) ?></div>
        </div>

        <div>
          <h5 class="break_page"><span aria-hidden="true" class="icon_ul icon-20"></span><?php echo $this->t('Pozycje') ?></h5>
          <ul>
          <?php foreach ($this->checklist->getItems() as $item): ?>
            <li><?php echo $this->escape($item->getName()) ?></li>
          <?php endforeach; ?>
          </ul>
        </div>
        <?php $this->filterRequestConditions($this->filterForm->getValues()) ?>
        <?php echo $this->partial('test/tasks.phtml', array(
          'tasksNumberRecords' => $this->tasksNumberRecords,
          'tasksPaginator' => $this->tasksPaginator,
          'tasksList' => $this->tasksList,
          'activeProject' => $this->activeProject,
          'filterForm' => $this->filterForm,
          'request' => $this->request
        )); ?>
      </div>
      <div class="contentEditUser_right">
        <div class="textLabelPropertiesDiv">
          <div class="textLabelEditor_text"><?php echo $this->t('Autor') ?>: </div>
          <div id="text" class="content_label"><?php echo $this->escapeQuotes($this->checklist->getAuthor()->getFullname()) ?></div>
        </div>
        <div class="textLabelPropertiesDiv" style="border-bottom:0px solid;">
          <div class="textLabelEditor_text"><?php echo $this->t('Data utworzenia') ?>: </div>
          <div id="text" class="content_label"> <?php echo $this->checklist->getCreateDate() ?></div>
        </div>
        <?php echo $this->partial('partials/attachments.phtml', array('attachments' => $this->checklist->getExtraData('attachments'))); ?>
      </div>

    </div>
  </article>
</section>

<?php echo $this->partial('popups/delete-tests.phtml'); ?>
<?php echo $this->partial('partials/multi-select-js.phtml'); ?>
  
  